window.COVERAGE_DATA = {
  "generated_at": "2026-06-10T23:22:07+00:00",
  "countries": {
    "AR": {
      "tier": "well_mapped",
      "n_includes": 177,
      "evidence_pct": 0.842,
      "n_patches": 3,
      "n_local_investors": 15
    },
    "BM": {
      "tier": "fuera_de_foco",
      "n_includes": 1,
      "evidence_pct": 0.0,
      "n_patches": 1,
      "n_local_investors": 0
    },
    "BR": {
      "tier": "well_mapped",
      "n_includes": 153,
      "evidence_pct": 0.444,
      "n_patches": 3,
      "n_local_investors": 33
    },
    "CL": {
      "tier": "partial",
      "n_includes": 70,
      "evidence_pct": 0.314,
      "n_patches": 3,
      "n_local_investors": 9
    },
    "CO": {
      "tier": "under_explored",
      "n_includes": 13,
      "evidence_pct": 0.692,
      "n_patches": 3,
      "n_local_investors": 1
    },
    "CR": {
      "tier": "under_explored",
      "n_includes": 7,
      "evidence_pct": 0.286,
      "n_patches": 2,
      "n_local_investors": 3
    },
    "GT": {
      "tier": "under_explored",
      "n_includes": 2,
      "evidence_pct": 0.0,
      "n_patches": 1,
      "n_local_investors": 0
    },
    "MX": {
      "tier": "partial",
      "n_includes": 41,
      "evidence_pct": 0.268,
      "n_patches": 2,
      "n_local_investors": 2
    },
    "NL": {
      "tier": "fuera_de_foco",
      "n_includes": 2,
      "evidence_pct": 1.0,
      "n_patches": 0,
      "n_local_investors": 0
    },
    "PA": {
      "tier": "under_explored",
      "n_includes": 1,
      "evidence_pct": 0.0,
      "n_patches": 1,
      "n_local_investors": 0
    },
    "PE": {
      "tier": "under_explored",
      "n_includes": 3,
      "evidence_pct": 0.333,
      "n_patches": 2,
      "n_local_investors": 1
    },
    "PR": {
      "tier": "fuera_de_foco",
      "n_includes": 2,
      "evidence_pct": 0.0,
      "n_patches": 1,
      "n_local_investors": 0
    },
    "US": {
      "tier": "fuera_de_foco",
      "n_includes": 12,
      "evidence_pct": 0.917,
      "n_patches": 2,
      "n_local_investors": 21
    },
    "UY": {
      "tier": "under_explored",
      "n_includes": 12,
      "evidence_pct": 0.583,
      "n_patches": 2,
      "n_local_investors": 0
    },
    "BE": {
      "tier": "fuera_de_foco",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 2
    },
    "CH": {
      "tier": "fuera_de_foco",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 1
    },
    "DE": {
      "tier": "fuera_de_foco",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 1
    },
    "ES": {
      "tier": "fuera_de_foco",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 1
    },
    "FI": {
      "tier": "fuera_de_foco",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 1
    },
    "FR": {
      "tier": "fuera_de_foco",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 1
    },
    "HK": {
      "tier": "fuera_de_foco",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 2
    },
    "IE": {
      "tier": "fuera_de_foco",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 1
    },
    "NO": {
      "tier": "fuera_de_foco",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 1
    },
    "EC": {
      "tier": "under_explored",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 0
    },
    "PY": {
      "tier": "under_explored",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 0
    },
    "BO": {
      "tier": "under_explored",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 0
    },
    "VE": {
      "tier": "under_explored",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 0
    },
    "DO": {
      "tier": "under_explored",
      "n_includes": 0,
      "evidence_pct": 0.0,
      "n_patches": 0,
      "n_local_investors": 0
    }
  },
  "cells": [
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "AR",
      "n_startups": 26,
      "evidence_pct": 0.885,
      "capital_pct": 0.962,
      "dominant_source": "gridx",
      "dominant_source_share": 0.577,
      "country_tier": "well_mapped",
      "coverage_label": "bien_mapeado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "BM",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "BO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "BR",
      "n_startups": 23,
      "evidence_pct": 0.522,
      "capital_pct": 0.609,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 0.478,
      "country_tier": "well_mapped",
      "coverage_label": "parcial"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "CL",
      "n_startups": 7,
      "evidence_pct": 0.429,
      "capital_pct": 0.857,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 0.571,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "CO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "CR",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 1.0,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "DO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "EC",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "GT",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "MX",
      "n_startups": 5,
      "evidence_pct": 0.0,
      "capital_pct": 0.2,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 0.6,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "NL",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "PA",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "PE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "PR",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "PY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "US",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "UY",
      "n_startups": 2,
      "evidence_pct": 0.0,
      "capital_pct": 0.5,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Bioinputs & Crop Resilience",
      "country": "VE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "AR",
      "n_startups": 10,
      "evidence_pct": 0.9,
      "capital_pct": 0.9,
      "dominant_source": "gridx",
      "dominant_source_share": 0.5,
      "country_tier": "well_mapped",
      "coverage_label": "bien_mapeado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "BM",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "BO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "BR",
      "n_startups": 9,
      "evidence_pct": 0.556,
      "capital_pct": 0.556,
      "dominant_source": "gridx",
      "dominant_source_share": 0.556,
      "country_tier": "well_mapped",
      "coverage_label": "parcial"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "CL",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "CO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "CR",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "DO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "EC",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "GT",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "MX",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "NL",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "PA",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "PE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "PR",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "PY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "US",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "UY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomanufacturing & Platform Technologies",
      "country": "VE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "AR",
      "n_startups": 21,
      "evidence_pct": 0.857,
      "capital_pct": 0.905,
      "dominant_source": "gridx",
      "dominant_source_share": 0.524,
      "country_tier": "well_mapped",
      "coverage_label": "bien_mapeado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "BM",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "BO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "BR",
      "n_startups": 7,
      "evidence_pct": 0.143,
      "capital_pct": 0.429,
      "dominant_source": "gridx",
      "dominant_source_share": 0.714,
      "country_tier": "well_mapped",
      "coverage_label": "parcial"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "CL",
      "n_startups": 12,
      "evidence_pct": 0.25,
      "capital_pct": 0.667,
      "dominant_source": "gridx",
      "dominant_source_share": 0.417,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "CO",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "CR",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "DO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "EC",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "GT",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "MX",
      "n_startups": 7,
      "evidence_pct": 0.286,
      "capital_pct": 0.571,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 0.571,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "NL",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "PA",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "PE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "PR",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "PY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "US",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "UY",
      "n_startups": 2,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Biomaterials & Circular Economy",
      "country": "VE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "AR",
      "n_startups": 45,
      "evidence_pct": 0.756,
      "capital_pct": 0.756,
      "dominant_source": "gridx",
      "dominant_source_share": 0.667,
      "country_tier": "well_mapped",
      "coverage_label": "bien_mapeado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "BM",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "BO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "BR",
      "n_startups": 31,
      "evidence_pct": 0.194,
      "capital_pct": 0.581,
      "dominant_source": "gridx",
      "dominant_source_share": 0.548,
      "country_tier": "well_mapped",
      "coverage_label": "parcial"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "CL",
      "n_startups": 14,
      "evidence_pct": 0.286,
      "capital_pct": 0.5,
      "dominant_source": "gridx",
      "dominant_source_share": 0.571,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "CO",
      "n_startups": 2,
      "evidence_pct": 0.5,
      "capital_pct": 1.0,
      "dominant_source": "summary_extraction",
      "dominant_source_share": 0.5,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "CR",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "DO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "EC",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "GT",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "MX",
      "n_startups": 11,
      "evidence_pct": 0.091,
      "capital_pct": 0.545,
      "dominant_source": "gridx",
      "dominant_source_share": 0.818,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "NL",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "PA",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "PE",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "PR",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "PY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "US",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "UY",
      "n_startups": 3,
      "evidence_pct": 0.667,
      "capital_pct": 0.667,
      "dominant_source": "gridx",
      "dominant_source_share": 0.667,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Diagnostics & Health Access",
      "country": "VE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "AR",
      "n_startups": 17,
      "evidence_pct": 0.941,
      "capital_pct": 0.941,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 0.647,
      "country_tier": "well_mapped",
      "coverage_label": "bien_mapeado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "BM",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Farm Intelligence",
      "country": "BO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "BR",
      "n_startups": 38,
      "evidence_pct": 0.763,
      "capital_pct": 0.842,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 0.526,
      "country_tier": "well_mapped",
      "coverage_label": "bien_mapeado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "CL",
      "n_startups": 4,
      "evidence_pct": 0.5,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 0.5,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Farm Intelligence",
      "country": "CO",
      "n_startups": 4,
      "evidence_pct": 1.0,
      "capital_pct": 0.75,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 0.5,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "CR",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "DO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "EC",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "GT",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "MX",
      "n_startups": 2,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 1.0,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Farm Intelligence",
      "country": "NL",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Farm Intelligence",
      "country": "PA",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "PE",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "PR",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Farm Intelligence",
      "country": "PY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "US",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Farm Intelligence",
      "country": "UY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Farm Intelligence",
      "country": "VE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "AR",
      "n_startups": 19,
      "evidence_pct": 0.842,
      "capital_pct": 0.947,
      "dominant_source": "gridx",
      "dominant_source_share": 0.579,
      "country_tier": "well_mapped",
      "coverage_label": "bien_mapeado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "BM",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "BO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "BR",
      "n_startups": 8,
      "evidence_pct": 0.375,
      "capital_pct": 0.5,
      "dominant_source": "gridx",
      "dominant_source_share": 0.75,
      "country_tier": "well_mapped",
      "coverage_label": "parcial"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "CL",
      "n_startups": 19,
      "evidence_pct": 0.211,
      "capital_pct": 0.526,
      "dominant_source": "gridx",
      "dominant_source_share": 0.684,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "CO",
      "n_startups": 3,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "CR",
      "n_startups": 2,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "DO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "EC",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "GT",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "MX",
      "n_startups": 11,
      "evidence_pct": 0.364,
      "capital_pct": 0.545,
      "dominant_source": "gridx",
      "dominant_source_share": 0.636,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "NL",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "PA",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "PE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "PR",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "PY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "US",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "UY",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Food Systems & Alt Proteins",
      "country": "VE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "AR",
      "n_startups": 14,
      "evidence_pct": 0.929,
      "capital_pct": 0.857,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 0.714,
      "country_tier": "well_mapped",
      "coverage_label": "parcial"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "BM",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "BO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "BR",
      "n_startups": 10,
      "evidence_pct": 0.8,
      "capital_pct": 0.9,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 0.6,
      "country_tier": "well_mapped",
      "coverage_label": "bien_mapeado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "CL",
      "n_startups": 5,
      "evidence_pct": 0.6,
      "capital_pct": 0.8,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 0.6,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "CO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "CR",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "DO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "EC",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "GT",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "MX",
      "n_startups": 3,
      "evidence_pct": 0.333,
      "capital_pct": 1.0,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 0.333,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "NL",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "PA",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "PE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "PR",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "PY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "US",
      "n_startups": 2,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "UY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Nature & Ecosystem Tech",
      "country": "VE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "AR",
      "n_startups": 25,
      "evidence_pct": 0.8,
      "capital_pct": 0.84,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 0.6,
      "country_tier": "well_mapped",
      "coverage_label": "bien_mapeado"
    },
    {
      "theme": "Therapeutics",
      "country": "BM",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Therapeutics",
      "country": "BO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "BR",
      "n_startups": 27,
      "evidence_pct": 0.148,
      "capital_pct": 0.37,
      "dominant_source": "gridx",
      "dominant_source_share": 0.667,
      "country_tier": "well_mapped",
      "coverage_label": "parcial"
    },
    {
      "theme": "Therapeutics",
      "country": "CL",
      "n_startups": 8,
      "evidence_pct": 0.25,
      "capital_pct": 0.75,
      "dominant_source": "gridx",
      "dominant_source_share": 0.5,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Therapeutics",
      "country": "CO",
      "n_startups": 3,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 0.333,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "CR",
      "n_startups": 2,
      "evidence_pct": 0.5,
      "capital_pct": 0.5,
      "dominant_source": "web_research_2026",
      "dominant_source_share": 0.5,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "DO",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "EC",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "GT",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "MX",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 1.0,
      "country_tier": "partial",
      "coverage_label": "parcial"
    },
    {
      "theme": "Therapeutics",
      "country": "NL",
      "n_startups": 1,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Therapeutics",
      "country": "PA",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "PE",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "PR",
      "n_startups": 1,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "gridx",
      "dominant_source_share": 1.0,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Therapeutics",
      "country": "PY",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "US",
      "n_startups": 5,
      "evidence_pct": 1.0,
      "capital_pct": 1.0,
      "dominant_source": "(sin provenance)",
      "dominant_source_share": 0.8,
      "country_tier": "fuera_de_foco",
      "coverage_label": "fuera_de_foco"
    },
    {
      "theme": "Therapeutics",
      "country": "UY",
      "n_startups": 4,
      "evidence_pct": 0.75,
      "capital_pct": 0.75,
      "dominant_source": "gridx",
      "dominant_source_share": 0.75,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    },
    {
      "theme": "Therapeutics",
      "country": "VE",
      "n_startups": 0,
      "evidence_pct": 0.0,
      "capital_pct": 0.0,
      "dominant_source": "",
      "dominant_source_share": 0.0,
      "country_tier": "under_explored",
      "coverage_label": "no_explorado"
    }
  ],
  "label_counts": {
    "bien_mapeado": 9,
    "fuera_de_foco": 32,
    "no_explorado": 88,
    "parcial": 23
  },
  "debias_queue_size": 88,
  "legend": {
    "bien_mapeado": "Volumen + evidencia externa + fuentes diversas: la celda es confiable.",
    "parcial": "Hay datos, pero con evidencia floja o dependientes de un solo parche.",
    "no_explorado": "País poco barrido: la ausencia NO significa inexistencia.",
    "fuera_de_foco": "País no-LATAM: presente por operación regional, no es objetivo de barrido.",
    "vacio_observado": "Cero startups en zona bien barrida: candidato a whitespace real."
  }
};
