window.ECOSYSTEM_DATA = {
  nodes: [
    { id: "gridx", label: "GridX", type: "capital", size: 40, source: "canonical" },
    { id: "uba", label: "Universidad de Buenos Aires", type: "university", size: 30, source: "rich_graph_extracted" },
    { id: "nxtp", label: "Nxtp Labs", type: "capital", size: 26, source: "visual_reference" },
    { id: "air", label: "Air Capital", type: "capital", size: 20, source: "canonical" },
    { id: "sf500", label: "SF500", type: "capital", size: 17, source: "canonical" },
    { id: "cites", label: "Cites", type: "capital", size: 15, source: "canonical" },
    { id: "kamay", label: "Kamay Ventures", type: "capital", size: 14, source: "visual_reference" },
    { id: "draper", label: "Draper Cygnus", type: "capital", size: 16, source: "canonical" },
    { id: "antom", label: "Antom", type: "capital", size: 12, source: "canonical" },
    { id: "indiebio", label: "IndieBio", type: "capital", size: 11, source: "canonical_and_rich_graph" },
    { id: "wayra", label: "Wayra Hispam", type: "capital", size: 10, source: "rich_graph_extracted" },
    { id: "ycombinator", label: "Y Combinator", type: "capital", size: 10, source: "rich_graph_extracted" },
    { id: "techstars", label: "Techstars", type: "capital", size: 9, source: "rich_graph_extracted" },
    { id: "fivehundred", label: "500 Startups", type: "capital", size: 9, source: "rich_graph_extracted" },
    { id: "brinc", label: "Brinc", type: "capital", size: 9, source: "rich_graph_extracted" },

    { id: "unl", label: "Universidad Nacional del Litoral", type: "university", size: 15, source: "rich_graph_extracted" },
    { id: "unr", label: "Universidad Nacional de Rosario", type: "university", size: 15, source: "rich_graph_extracted" },
    { id: "unc", label: "Universidad Nacional de Córdoba", type: "university", size: 13, source: "rich_graph_extracted" },
    { id: "uncuyo", label: "Universidad Nacional de Cuyo", type: "university", size: 12, source: "rich_graph_extracted" },
    { id: "unt", label: "Universidad Nacional de Tucumán", type: "university", size: 12, source: "rich_graph_extracted" },
    { id: "unlp", label: "Universidad Nacional de La Plata", type: "university", size: 12, source: "rich_graph_extracted" },
    { id: "itba", label: "ITBA", type: "university", size: 10, source: "rich_graph_extracted" },
    { id: "instituto_leloir", label: "Instituto Leloir", type: "university", size: 10, source: "rich_graph_extracted" },
    { id: "conicet", label: "CONICET", type: "university", size: 11, source: "rich_graph_extracted" },
    { id: "inta", label: "INTA Castelar", type: "university", size: 9, source: "rich_graph_extracted" },
    { id: "ifir", label: "IFIR", type: "university", size: 8, source: "rich_graph_extracted" },
    { id: "iprobyq", label: "IPROBYQ", type: "university", size: 8, source: "rich_graph_extracted" },
    { id: "ial", label: "IAL (CONICET-UNL)", type: "university", size: 8, source: "rich_graph_extracted" },
    { id: "iquibicen", label: "IQUIBICEN", type: "university", size: 8, source: "rich_graph_extracted" },
    { id: "pasteur", label: "Institut Pasteur Montevideo", type: "university", size: 8, source: "rich_graph_extracted" },
    { id: "udesa", label: "UdeSA", type: "university", size: 8, source: "rich_graph_extracted" },
    { id: "iae", label: "IAE Business School", type: "university", size: 8, source: "rich_graph_extracted" },
    { id: "ucema", label: "UCEMA", type: "university", size: 7, source: "rich_graph_extracted" },
    { id: "draper_university", label: "Draper University", type: "university", size: 8, source: "rich_graph_extracted" },

    { id: "stamm", label: "Stämm", type: "startup", size: 13, source: "canonical" },
    { id: "beeflow", label: "Beeflow", type: "startup", size: 11, source: "canonical" },
    { id: "caspr", label: "CASPR", type: "startup", size: 10, source: "canonical" },
    { id: "michroma", label: "Michroma", type: "startup", size: 10, source: "canonical" },
    { id: "punabio", label: "Puna Bio", type: "startup", size: 9, source: "canonical" },
    { id: "feedvax", label: "Feedvax", type: "startup", size: 8, source: "canonical" },
    { id: "cellfarm", label: "Cell Farm", type: "startup", size: 8, source: "canonical" },
    { id: "argentag", label: "ArgenTAG", type: "startup", size: 8, source: "canonical" },
    { id: "tomorrow", label: "Tomorrow Foods", type: "startup", size: 8, source: "canonical" },
    { id: "bioeutectics", label: "Bioeutectics", type: "startup", size: 8, source: "canonical" },
    { id: "zev", label: "ZEV Biotech", type: "startup", size: 7, source: "canonical" },
    { id: "limay", label: "Limay Biosciences", type: "startup", size: 7, source: "canonical" },
    { id: "vexxel", label: "Vexxel Biotech", type: "startup", size: 7, source: "canonical" },
    { id: "ubique", label: "Ubique Bio", type: "startup", size: 7, source: "canonical" },
    { id: "kresko", label: "Kresko RNATech", type: "startup", size: 7, source: "canonical" },
    { id: "satellogic", label: "Satellogic", type: "startup", size: 10, source: "rich_graph_extracted" },
    { id: "auth0", label: "Auth0", type: "startup", size: 10, source: "rich_graph_extracted" },
    { id: "kilimo", label: "Kilimo", type: "startup", size: 8, source: "rich_graph_extracted" },
    { id: "polymera", label: "Polymera", type: "startup", size: 7, source: "rich_graph_extracted" },
    { id: "migma", label: "Migma", type: "startup", size: 7, source: "rich_graph_extracted" },
    { id: "nairotech", label: "Nairotech", type: "startup", size: 6, source: "rich_graph_extracted" },
    { id: "inbioar", label: "Inbioar", type: "startup", size: 6, source: "rich_graph_extracted" },
    { id: "infira", label: "Infira", type: "startup", size: 6, source: "rich_graph_extracted" },
    { id: "neworgans", label: "New Organs Biotech", type: "startup", size: 7, source: "canonical" },
    { id: "oncoprecision", label: "Onco Precision", type: "startup", size: 7, source: "canonical" },
    { id: "nanotica", label: "Nanotica", type: "startup", size: 6, source: "rich_graph_extracted" },
    { id: "nat4bio", label: "Nat4Bio", type: "startup", size: 6, source: "rich_graph_extracted" },
    { id: "nanotransfer", label: "NanoTransfer", type: "startup", size: 6, source: "rich_graph_extracted" },
    { id: "nanoingreen", label: "NanoInGreen", type: "startup", size: 6, source: "rich_graph_extracted" },
    { id: "protiva", label: "Protiva", type: "startup", size: 6, source: "rich_graph_extracted" }
  ],
  edges: [
    { source: "gridx", target: "stamm", kind: "capital", confidence: "high" },
    { source: "gridx", target: "beeflow", kind: "capital", confidence: "high" },
    { source: "gridx", target: "michroma", kind: "capital", confidence: "high" },
    { source: "gridx", target: "punabio", kind: "capital", confidence: "high" },
    { source: "gridx", target: "feedvax", kind: "capital", confidence: "high" },
    { source: "gridx", target: "cellfarm", kind: "capital", confidence: "high" },
    { source: "gridx", target: "argentag", kind: "capital", confidence: "high" },
    { source: "gridx", target: "tomorrow", kind: "capital", confidence: "high" },
    { source: "gridx", target: "bioeutectics", kind: "capital", confidence: "high" },
    { source: "gridx", target: "zev", kind: "capital", confidence: "high" },
    { source: "gridx", target: "limay", kind: "capital", confidence: "high" },
    { source: "gridx", target: "vexxel", kind: "capital", confidence: "high" },
    { source: "gridx", target: "ubique", kind: "capital", confidence: "high" },
    { source: "gridx", target: "kresko", kind: "capital", confidence: "high" },
    { source: "gridx", target: "neworgans", kind: "capital", confidence: "medium" },
    { source: "gridx", target: "oncoprecision", kind: "capital", confidence: "medium" },

    { source: "air", target: "stamm", kind: "capital", confidence: "high" },
    { source: "air", target: "beeflow", kind: "capital", confidence: "high" },
    { source: "air", target: "caspr", kind: "capital", confidence: "high" },
    { source: "air", target: "michroma", kind: "capital", confidence: "high" },
    { source: "air", target: "punabio", kind: "capital", confidence: "high" },
    { source: "air", target: "polymera", kind: "capital", confidence: "medium" },
    { source: "air", target: "migma", kind: "capital", confidence: "medium" },
    { source: "air", target: "nairotech", kind: "capital", confidence: "medium" },
    { source: "air", target: "inbioar", kind: "capital", confidence: "medium" },
    { source: "air", target: "infira", kind: "capital", confidence: "medium" },

    { source: "sf500", target: "bioeutectics", kind: "capital", confidence: "high" },
    { source: "sf500", target: "limay", kind: "capital", confidence: "high" },
    { source: "sf500", target: "zev", kind: "capital", confidence: "high" },
    { source: "sf500", target: "nat4bio", kind: "capital", confidence: "medium" },

    { source: "cites", target: "vexxel", kind: "capital", confidence: "high" },
    { source: "cites", target: "limay", kind: "capital", confidence: "high" },
    { source: "cites", target: "ubique", kind: "capital", confidence: "medium" },

    { source: "kamay", target: "kilimo", kind: "capital", confidence: "medium" },
    { source: "kamay", target: "bioeutectics", kind: "capital", confidence: "medium" },
    { source: "kamay", target: "migma", kind: "capital", confidence: "medium" },

    { source: "draper", target: "stamm", kind: "capital", confidence: "high" },
    { source: "draper", target: "beeflow", kind: "capital", confidence: "high" },
    { source: "draper", target: "satellogic", kind: "capital", confidence: "medium" },

    { source: "antom", target: "kilimo", kind: "capital", confidence: "high" },
    { source: "indiebio", target: "stamm", kind: "capital", confidence: "high" },
    { source: "indiebio", target: "beeflow", kind: "capital", confidence: "high" },
    { source: "indiebio", target: "neworgans", kind: "capital", confidence: "medium" },
    { source: "ycombinator", target: "auth0", kind: "capital", confidence: "medium" },
    { source: "wayra", target: "satellogic", kind: "capital", confidence: "medium" },
    { source: "techstars", target: "kilimo", kind: "capital", confidence: "low" },
    { source: "fivehundred", target: "auth0", kind: "capital", confidence: "low" },
    { source: "brinc", target: "michroma", kind: "capital", confidence: "low" },

    { source: "uba", target: "stamm", kind: "institution", confidence: "medium" },
    { source: "uba", target: "caspr", kind: "institution", confidence: "medium" },
    { source: "uba", target: "neworgans", kind: "institution", confidence: "medium" },
    { source: "uba", target: "cellfarm", kind: "institution", confidence: "medium" },
    { source: "uba", target: "oncoprecision", kind: "institution", confidence: "medium" },
    { source: "uba", target: "auth0", kind: "institution", confidence: "low" },

    { source: "unl", target: "bioeutectics", kind: "institution", confidence: "medium" },
    { source: "unl", target: "limay", kind: "institution", confidence: "medium" },
    { source: "unl", target: "feedvax", kind: "institution", confidence: "low" },
    { source: "unr", target: "beeflow", kind: "institution", confidence: "medium" },
    { source: "unr", target: "feedvax", kind: "institution", confidence: "medium" },
    { source: "unc", target: "michroma", kind: "institution", confidence: "medium" },
    { source: "unc", target: "kresko", kind: "institution", confidence: "medium" },
    { source: "uncuyo", target: "kilimo", kind: "institution", confidence: "medium" },
    { source: "unt", target: "argentag", kind: "institution", confidence: "low" },
    { source: "unlp", target: "argentag", kind: "institution", confidence: "medium" },
    { source: "itba", target: "stamm", kind: "institution", confidence: "medium" },
    { source: "instituto_leloir", target: "vexxel", kind: "institution", confidence: "medium" },
    { source: "instituto_leloir", target: "neworgans", kind: "institution", confidence: "medium" },
    { source: "conicet", target: "stamm", kind: "institution", confidence: "medium" },
    { source: "conicet", target: "beeflow", kind: "institution", confidence: "medium" },
    { source: "conicet", target: "michroma", kind: "institution", confidence: "medium" },
    { source: "conicet", target: "punabio", kind: "institution", confidence: "medium" },
    { source: "inta", target: "punabio", kind: "institution", confidence: "low" },
    { source: "ifir", target: "michroma", kind: "institution", confidence: "low" },
    { source: "iprobyq", target: "beeflow", kind: "institution", confidence: "low" },
    { source: "ial", target: "bioeutectics", kind: "institution", confidence: "low" },
    { source: "iquibicen", target: "cellfarm", kind: "institution", confidence: "low" },
    { source: "pasteur", target: "oncoprecision", kind: "institution", confidence: "low" },
    { source: "udesa", target: "auth0", kind: "institution", confidence: "low" },
    { source: "iae", target: "kilimo", kind: "institution", confidence: "low" },
    { source: "ucema", target: "satellogic", kind: "institution", confidence: "low" },
    { source: "draper_university", target: "stamm", kind: "institution", confidence: "low" },

    { source: "uba", target: "gridx", kind: "bridge", confidence: "low" },
    { source: "uba", target: "air", kind: "bridge", confidence: "low" },
    { source: "uba", target: "sf500", kind: "bridge", confidence: "low" },
    { source: "uba", target: "draper", kind: "bridge", confidence: "low" },
    { source: "unl", target: "cites", kind: "bridge", confidence: "low" },
    { source: "unr", target: "gridx", kind: "bridge", confidence: "low" },
    { source: "unc", target: "air", kind: "bridge", confidence: "low" },
    { source: "uncuyo", target: "kamay", kind: "bridge", confidence: "low" },
    { source: "itba", target: "gridx", kind: "bridge", confidence: "low" },
    { source: "instituto_leloir", target: "cites", kind: "bridge", confidence: "low" },
    { source: "nxtp", target: "auth0", kind: "capital", confidence: "medium" },
    { source: "nxtp", target: "satellogic", kind: "capital", confidence: "medium" }
  ]
};
