"""Script temporal para escribir batch de tags directamente a entity_enrichments.csv"""
import csv, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
out = ROOT / "staging" / "entity_enrichments.csv"
date = "2026-06-25"
src = "swarm_inline_sonnet_v1"

# (entity_id, field, value, confidence)
batch1 = [
  ("innmetec-co",              "bio_lens_tags",    "human-health-bio",                                    0.90),
  ("innmetec-co",              "domain_tags",      "diagnostics-medtech",                                 0.90),
  ("innmetec-co",              "technology_tags",  "biomaterials,diagnostics",                            0.90),
  ("innmetec-co",              "scale_tags",       "human-scale,product-scale",                           0.90),
  ("forma-foods-mx",           "bio_lens_tags",    "biobased",                                            0.85),
  ("forma-foods-mx",           "domain_tags",      "agri-food,biomanufacturing",                          0.85),
  ("forma-foods-mx",           "technology_tags",  "precision-fermentation",                              0.85),
  ("forma-foods-mx",           "scale_tags",       "product-scale",                                       0.85),
  ("koji-co",                  "bio_lens_tags",    "biobased,circular",                                   0.92),
  ("koji-co",                  "domain_tags",      "agri-food,biomanufacturing",                          0.92),
  ("koji-co",                  "technology_tags",  "fermentation",                                        0.92),
  ("koji-co",                  "scale_tags",       "product-scale,industrial-scale",                      0.92),
  ("global-nano-additives-mx", "bio_lens_tags",    "bio-enabled-industrial-transition",                   0.80),
  ("global-nano-additives-mx", "domain_tags",      "industrial-biotech",                                  0.80),
  ("global-nano-additives-mx", "technology_tags",  "biomaterials",                                        0.80),
  ("global-nano-additives-mx", "scale_tags",       "product-scale,industrial-scale",                      0.80),
  ("bioram-mx",                "bio_lens_tags",    "biobased,circular",                                   0.92),
  ("bioram-mx",                "domain_tags",      "agri-food",                                           0.92),
  ("bioram-mx",                "technology_tags",  "bioinputs,fermentation",                              0.92),
  ("bioram-mx",                "scale_tags",       "agroecosystem-scale,industrial-scale",                0.92),
  ("tissue-nova-mx",           "bio_lens_tags",    "human-health-bio",                                    0.90),
  ("tissue-nova-mx",           "domain_tags",      "diagnostics-medtech,therapeutics-regenerative",       0.90),
  ("tissue-nova-mx",           "technology_tags",  "therapeutics,diagnostics",                            0.90),
  ("tissue-nova-mx",           "scale_tags",       "molecular-scale,human-scale",                         0.90),
  ("fieldfactors-mx",          "bio_lens_tags",    "planetary-boundary",                                  0.85),
  ("fieldfactors-mx",          "domain_tags",      "climate-resource",                                    0.85),
  ("fieldfactors-mx",          "technology_tags",  "iot",                                                 0.85),
  ("fieldfactors-mx",          "scale_tags",       "agroecosystem-scale,territorial-scale",               0.85),
  ("biorefinery-tech-brazil-br","bio_lens_tags",   "biobased,circular,bio-enabled-industrial-transition", 0.88),
  ("biorefinery-tech-brazil-br","domain_tags",     "biomanufacturing,industrial-biotech",                 0.88),
  ("biorefinery-tech-brazil-br","technology_tags", "fermentation,biomanufacturing",                       0.88),
  ("biorefinery-tech-brazil-br","scale_tags",      "industrial-scale",                                    0.88),
  ("infood-protein-cl",        "bio_lens_tags",    "biobased,circular",                                   0.92),
  ("infood-protein-cl",        "domain_tags",      "agri-food,biomanufacturing",                          0.92),
  ("infood-protein-cl",        "technology_tags",  "fermentation,bioinputs",                              0.92),
  ("infood-protein-cl",        "scale_tags",       "product-scale,industrial-scale",                      0.92),
  ("aquabyte-cl",              "bio_lens_tags",    "biocentric",                                          0.88),
  ("aquabyte-cl",              "domain_tags",      "agri-food",                                           0.88),
  ("aquabyte-cl",              "technology_tags",  "ai-data,remote-sensing",                              0.88),
  ("aquabyte-cl",              "scale_tags",       "agroecosystem-scale",                                 0.88),
  ("savefruit-mx",             "bio_lens_tags",    "biobased,circular",                                   0.88),
  ("savefruit-mx",             "domain_tags",      "agri-food",                                           0.88),
  ("savefruit-mx",             "technology_tags",  "biomaterials",                                        0.88),
  ("savefruit-mx",             "scale_tags",       "product-scale,agroecosystem-scale",                   0.88),
  ("wseeds-co",                "bio_lens_tags",    "biocentric",                                          0.82),
  ("wseeds-co",                "domain_tags",      "agri-food",                                           0.82),
  ("wseeds-co",                "technology_tags",  "ai-data,iot",                                         0.82),
  ("wseeds-co",                "scale_tags",       "agroecosystem-scale",                                 0.82),
  ("kran-nanobubble-cl",       "bio_lens_tags",    "planetary-boundary",                                  0.85),
  ("kran-nanobubble-cl",       "domain_tags",      "climate-resource,agri-food",                          0.85),
  ("kran-nanobubble-cl",       "technology_tags",  "iot",                                                 0.85),
  ("kran-nanobubble-cl",       "scale_tags",       "agroecosystem-scale,industrial-scale",                0.85),
  ("nalca-biotech-cl",         "bio_lens_tags",    "biobased,bio-enabled-industrial-transition",          0.92),
  ("nalca-biotech-cl",         "domain_tags",      "biomanufacturing",                                    0.92),
  ("nalca-biotech-cl",         "technology_tags",  "precision-fermentation,biomanufacturing",             0.92),
  ("nalca-biotech-cl",         "scale_tags",       "industrial-scale,molecular-scale",                    0.92),
  ("exacta-bioscience-cl",     "bio_lens_tags",    "biobased,biocentric",                                 0.93),
  ("exacta-bioscience-cl",     "domain_tags",      "agri-food",                                           0.93),
  ("exacta-bioscience-cl",     "technology_tags",  "bioinputs,synthetic-biology",                         0.93),
  ("exacta-bioscience-cl",     "scale_tags",       "agroecosystem-scale,molecular-scale",                 0.93),
  ("merken-biotech-cl",        "bio_lens_tags",    "human-health-bio,biocentric",                         0.90),
  ("merken-biotech-cl",        "domain_tags",      "diagnostics-medtech,therapeutics-regenerative",       0.90),
  ("merken-biotech-cl",        "technology_tags",  "diagnostics,therapeutics",                            0.90),
  ("merken-biotech-cl",        "scale_tags",       "molecular-scale,human-scale",                         0.90),
  ("pow_foods",                "bio_lens_tags",    "biobased",                                            0.88),
  ("pow_foods",                "domain_tags",      "agri-food",                                           0.88),
  ("pow_foods",                "technology_tags",  "fermentation",                                        0.88),
  ("pow_foods",                "scale_tags",       "product-scale",                                       0.88),
  ("quipu-cr",                 "bio_lens_tags",    "biocentric",                                          0.78),
  ("quipu-cr",                 "domain_tags",      "agri-food",                                           0.78),
  ("quipu-cr",                 "technology_tags",  "ai-data",                                             0.78),
  ("quipu-cr",                 "scale_tags",       "agroecosystem-scale",                                 0.78),
  ("bioblends",                "bio_lens_tags",    "biobased,circular",                                   0.90),
  ("bioblends",                "domain_tags",      "agri-food",                                           0.90),
  ("bioblends",                "technology_tags",  "bioinputs",                                           0.90),
  ("bioblends",                "scale_tags",       "product-scale",                                       0.90),
  ("krtl-biotech-bolivia-expansion-bo","bio_lens_tags","human-health-bio",                                0.85),
  ("krtl-biotech-bolivia-expansion-bo","domain_tags",  "therapeutics-regenerative",                       0.85),
  ("krtl-biotech-bolivia-expansion-bo","technology_tags","therapeutics",                                  0.85),
  ("krtl-biotech-bolivia-expansion-bo","scale_tags",    "molecular-scale,human-scale",                    0.85),
  ("kheiron-biotech-ar",       "bio_lens_tags",    "biobased,biocentric",                                 0.88),
  ("kheiron-biotech-ar",       "domain_tags",      "agri-food",                                           0.88),
  ("kheiron-biotech-ar",       "technology_tags",  "synthetic-biology",                                   0.88),
  ("kheiron-biotech-ar",       "scale_tags",       "molecular-scale,agroecosystem-scale",                 0.88),
  ("bontix-do",                "bio_lens_tags",    "biocentric",                                          0.80),
  ("bontix-do",                "domain_tags",      "agri-food",                                           0.80),
  ("bontix-do",                "technology_tags",  "iot,ai-data",                                         0.80),
  ("bontix-do",                "scale_tags",       "agroecosystem-scale",                                 0.80),
  ("agrobit-bolivia-operations-bo","bio_lens_tags","biocentric",                                          0.80),
  ("agrobit-bolivia-operations-bo","domain_tags",  "agri-food",                                           0.80),
  ("agrobit-bolivia-operations-bo","technology_tags","ai-data",                                           0.80),
  ("agrobit-bolivia-operations-bo","scale_tags",   "agroecosystem-scale,territorial-scale",               0.80),
  ("ejido-verde-mx",           "bio_lens_tags",    "biocentric,regenerative,circular",                    0.92),
  ("ejido-verde-mx",           "domain_tags",      "biodiversity-nature,climate-resource",                0.92),
  ("ejido-verde-mx",           "technology_tags",  "carbon-mrv",                                          0.92),
  ("ejido-verde-mx",           "scale_tags",       "territorial-scale,agroecosystem-scale",               0.92),
  ("bioplast-br",              "bio_lens_tags",    "biobased,circular",                                   0.88),
  ("bioplast-br",              "domain_tags",      "biomaterials",                                        0.88),
  ("bioplast-br",              "technology_tags",  "biomaterials",                                        0.88),
  ("bioplast-br",              "scale_tags",       "product-scale,industrial-scale",                      0.88),
]

with open(out, "a", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    for eid, field, val, conf in batch1:
        w.writerow([eid, "startup_extended", field, val, src, conf, f"swarm_inline_tags {date}"])

total = sum(1 for _ in open(out, encoding="utf-8")) - 1
print(f"Batch 1 escrito: {len(batch1)} filas. Total en entity_enrichments.csv: {total} filas")
