"""Batch 4 de tags inline — 23 startups nuevas (skip nalca-biotech-cl, quipu-cr ya hechas)."""
import csv, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
out = ROOT / "staging" / "entity_enrichments.csv"
date = "2026-06-25"
src = "swarm_inline_sonnet_v1"

batch4 = [
  ("microbiota-agricola-br","bio_lens_tags","biocentric,biobased",                                  0.92),
  ("microbiota-agricola-br","domain_tags",  "agri-food",                                            0.92),
  ("microbiota-agricola-br","technology_tags","bioinputs",                                          0.92),
  ("microbiota-agricola-br","scale_tags",   "agroecosystem-scale",                                  0.92),
  ("microlabs-mx",   "bio_lens_tags","biocentric,biobased",                                         0.90),
  ("microlabs-mx",   "domain_tags",  "agri-food",                                                   0.90),
  ("microlabs-mx",   "technology_tags","bioinputs",                                                 0.90),
  ("microlabs-mx",   "scale_tags",   "agroecosystem-scale",                                         0.90),
  ("minerba-ec",     "bio_lens_tags","planetary-boundary",                                           0.70),
  ("minerba-ec",     "domain_tags",  "climate-resource",                                             0.70),
  ("minerba-ec",     "technology_tags","ai-data",                                                   0.70),
  ("minerba-ec",     "scale_tags",   "territorial-scale,industrial-scale",                          0.70),
  ("mycoseaweed-cl", "bio_lens_tags","biobased,circular",                                            0.92),
  ("mycoseaweed-cl", "domain_tags",  "agri-food,biomanufacturing",                                  0.92),
  ("mycoseaweed-cl", "technology_tags","fermentation,bioinputs",                                    0.92),
  ("mycoseaweed-cl", "scale_tags",   "product-scale,industrial-scale",                              0.92),
  ("myvac-bioproducts-br","bio_lens_tags","biobased,bio-enabled-industrial-transition",             0.90),
  ("myvac-bioproducts-br","domain_tags",  "biomanufacturing",                                       0.90),
  ("myvac-bioproducts-br","technology_tags","enzymes,biomanufacturing",                             0.90),
  ("myvac-bioproducts-br","scale_tags",   "industrial-scale",                                       0.90),
  ("nanomedical-cr", "bio_lens_tags","human-health-bio",                                             0.82),
  ("nanomedical-cr", "domain_tags",  "diagnostics-medtech",                                         0.82),
  ("nanomedical-cr", "technology_tags","diagnostics",                                               0.82),
  ("nanomedical-cr", "scale_tags",   "human-scale",                                                  0.82),
  ("nemacontrol-biologicos-br","bio_lens_tags","biocentric,biobased",                               0.93),
  ("nemacontrol-biologicos-br","domain_tags",  "agri-food",                                         0.93),
  ("nemacontrol-biologicos-br","technology_tags","bioinputs",                                       0.93),
  ("nemacontrol-biologicos-br","scale_tags",   "agroecosystem-scale",                               0.93),
  ("neocroptech-cl", "bio_lens_tags","biocentric,biobased",                                         0.90),
  ("neocroptech-cl", "domain_tags",  "agri-food",                                                   0.90),
  ("neocroptech-cl", "technology_tags","synthetic-biology",                                         0.90),
  ("neocroptech-cl", "scale_tags",   "agroecosystem-scale",                                         0.90),
  ("nutrissis-biotech-br","bio_lens_tags","biobased",                                               0.90),
  ("nutrissis-biotech-br","domain_tags",  "agri-food,biomanufacturing",                             0.90),
  ("nutrissis-biotech-br","technology_tags","synthetic-biology,fermentation",                       0.90),
  ("nutrissis-biotech-br","scale_tags",   "molecular-scale,product-scale",                          0.90),
  ("oncoprecision-ar","bio_lens_tags","human-health-bio",                                            0.93),
  ("oncoprecision-ar","domain_tags",  "therapeutics-regenerative",                                   0.93),
  ("oncoprecision-ar","technology_tags","therapeutics,ai-data",                                     0.93),
  ("oncoprecision-ar","scale_tags",   "molecular-scale,human-scale",                                 0.93),
  ("pewman-innovation-cl","bio_lens_tags","biocentric,biobased",                                    0.92),
  ("pewman-innovation-cl","domain_tags",  "agri-food",                                               0.92),
  ("pewman-innovation-cl","technology_tags","bioinputs",                                             0.92),
  ("pewman-innovation-cl","scale_tags",   "agroecosystem-scale",                                     0.92),
  ("plantverd-mx",   "bio_lens_tags","biocentric,regenerative",                                      0.90),
  ("plantverd-mx",   "domain_tags",  "biodiversity-nature",                                          0.90),
  ("plantverd-mx",   "technology_tags","remediation",                                               0.90),
  ("plantverd-mx",   "scale_tags",   "territorial-scale,agroecosystem-scale",                       0.90),
  ("protera-bio-cl", "bio_lens_tags","biobased",                                                     0.92),
  ("protera-bio-cl", "domain_tags",  "agri-food,biomanufacturing",                                  0.92),
  ("protera-bio-cl", "technology_tags","synthetic-biology,ai-data",                                 0.92),
  ("protera-bio-cl", "scale_tags",   "molecular-scale,product-scale",                               0.92),
  ("recirculab-cl",  "bio_lens_tags","biocentric,circular",                                          0.88),
  ("recirculab-cl",  "domain_tags",  "agri-food,climate-resource",                                  0.88),
  ("recirculab-cl",  "technology_tags","remediation",                                               0.88),
  ("recirculab-cl",  "scale_tags",   "agroecosystem-scale",                                         0.88),
  ("recombine-biotech-br","bio_lens_tags","biocentric,biobased",                                    0.92),
  ("recombine-biotech-br","domain_tags",  "agri-food",                                               0.92),
  ("recombine-biotech-br","technology_tags","bioinputs,fermentation",                               0.92),
  ("recombine-biotech-br","scale_tags",   "agroecosystem-scale,molecular-scale",                    0.92),
  ("respiratorydx-co","bio_lens_tags","human-health-bio",                                            0.92),
  ("respiratorydx-co","domain_tags",  "diagnostics-medtech",                                         0.92),
  ("respiratorydx-co","technology_tags","diagnostics,ai-data",                                      0.92),
  ("respiratorydx-co","scale_tags",   "human-scale,product-scale",                                   0.92),
  ("salmoss-biotech-cl","bio_lens_tags","biocentric",                                                0.88),
  ("salmoss-biotech-cl","domain_tags",  "agri-food",                                                  0.88),
  ("salmoss-biotech-cl","technology_tags","ai-data,diagnostics",                                     0.88),
  ("salmoss-biotech-cl","scale_tags",   "agroecosystem-scale",                                        0.88),
  ("scintia-mx",     "bio_lens_tags","bio-enabled-industrial-transition",                             0.72),
  ("scintia-mx",     "domain_tags",  "biomanufacturing",                                              0.72),
  ("scintia-mx",     "technology_tags","ai-data",                                                    0.72),
  ("scintia-mx",     "scale_tags",   "human-scale",                                                   0.72),
  ("seedtech-cl",    "bio_lens_tags","biocentric,biobased",                                           0.88),
  ("seedtech-cl",    "domain_tags",  "agri-food",                                                     0.88),
  ("seedtech-cl",    "technology_tags","bioinputs",                                                   0.88),
  ("seedtech-cl",    "scale_tags",   "agroecosystem-scale,product-scale",                             0.88),
  ("silicochem-ec",  "bio_lens_tags","biobased",                                                      0.90),
  ("silicochem-ec",  "domain_tags",  "agri-food,biomanufacturing",                                   0.90),
  ("silicochem-ec",  "technology_tags","synthetic-biology,fermentation",                             0.90),
  ("silicochem-ec",  "scale_tags",   "molecular-scale,industrial-scale",                             0.90),
  ("swebol-biotech-bo","bio_lens_tags","biobased,biocentric",                                        0.88),
  ("swebol-biotech-bo","domain_tags",  "agri-food",                                                   0.88),
  ("swebol-biotech-bo","technology_tags","bioinputs",                                                 0.88),
  ("swebol-biotech-bo","scale_tags",   "agroecosystem-scale",                                         0.88),
  ("terrasos-br",    "bio_lens_tags","biocentric,regenerative",                                       0.92),
  ("terrasos-br",    "domain_tags",  "biodiversity-nature",                                           0.92),
  ("terrasos-br",    "technology_tags","carbon-mrv",                                                  0.92),
  ("terrasos-br",    "scale_tags",   "territorial-scale",                                             0.92),
  ("tierra-de-monte-mx","bio_lens_tags","biocentric,biobased,regenerative",                           0.92),
  ("tierra-de-monte-mx","domain_tags",  "agri-food",                                                  0.92),
  ("tierra-de-monte-mx","technology_tags","bioinputs",                                                0.92),
  ("tierra-de-monte-mx","scale_tags",   "agroecosystem-scale",                                        0.92),
]

with open(out, "a", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    for eid, field, val, conf in batch4:
        w.writerow([eid, "startup_extended", field, val, src, conf, f"swarm_inline_tags {date}"])

total = sum(1 for _ in open(out, encoding="utf-8")) - 1
print(f"Batch 4: {len(batch4)} filas. Total entity_enrichments: {total}")
