"""Batch 2 de tags inline — 21 startups nuevas (offset 25, sin los 4 overlap de batch 1)."""
import csv, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
out = ROOT / "staging" / "entity_enrichments.csv"
date = "2026-06-25"
src = "swarm_inline_sonnet_v1"

batch2 = [
  ("bioprocess-automation-brasil-br","bio_lens_tags","bio-enabled-industrial-transition",           0.88),
  ("bioprocess-automation-brasil-br","domain_tags",  "biomanufacturing",                            0.88),
  ("bioprocess-automation-brasil-br","technology_tags","fermentation,biomanufacturing",             0.88),
  ("bioprocess-automation-brasil-br","scale_tags",   "industrial-scale",                            0.88),
  ("bioproducts-co",  "bio_lens_tags","biobased",                                                   0.80),
  ("bioproducts-co",  "domain_tags",  "biomanufacturing",                                           0.80),
  ("bioproducts-co",  "technology_tags","fermentation,biomanufacturing",                            0.80),
  ("bioproducts-co",  "scale_tags",   "industrial-scale",                                           0.80),
  ("biotech-cr",      "bio_lens_tags","biocentric,biobased",                                        0.90),
  ("biotech-cr",      "domain_tags",  "agri-food",                                                  0.90),
  ("biotech-cr",      "technology_tags","bioinputs",                                                0.90),
  ("biotech-cr",      "scale_tags",   "agroecosystem-scale",                                        0.90),
  ("bioceres-ar",     "bio_lens_tags","biocentric,biobased",                                        0.93),
  ("bioceres-ar",     "domain_tags",  "agri-food",                                                  0.93),
  ("bioceres-ar",     "technology_tags","synthetic-biology",                                        0.93),
  ("bioceres-ar",     "scale_tags",   "agroecosystem-scale",                                        0.93),
  ("biogenesis-bago-ec","bio_lens_tags","human-health-bio,biocentric",                              0.85),
  ("biogenesis-bago-ec","domain_tags", "agri-food",                                                 0.85),
  ("biogenesis-bago-ec","technology_tags","therapeutics,diagnostics",                               0.85),
  ("biogenesis-bago-ec","scale_tags",  "agroecosystem-scale,human-scale",                          0.85),
  ("biolinker-br",    "bio_lens_tags","biobased",                                                   0.92),
  ("biolinker-br",    "domain_tags",  "biomanufacturing,therapeutics-regenerative",                 0.92),
  ("biolinker-br",    "technology_tags","synthetic-biology,fermentation",                           0.92),
  ("biolinker-br",    "scale_tags",   "molecular-scale,industrial-scale",                           0.92),
  ("cepha-biotech-br","bio_lens_tags","human-health-bio",                                           0.90),
  ("cepha-biotech-br","domain_tags",  "diagnostics-medtech",                                        0.90),
  ("cepha-biotech-br","technology_tags","diagnostics,synthetic-biology",                            0.90),
  ("cepha-biotech-br","scale_tags",   "human-scale,product-scale",                                  0.90),
  ("caribbean-medtech-do","bio_lens_tags","human-health-bio",                                       0.70),
  ("caribbean-medtech-do","domain_tags", "diagnostics-medtech",                                     0.70),
  ("caribbean-medtech-do","technology_tags","diagnostics",                                          0.70),
  ("caribbean-medtech-do","scale_tags",   "human-scale",                                            0.70),
  ("cellculture-br",  "bio_lens_tags","bio-enabled-industrial-transition",                          0.90),
  ("cellculture-br",  "domain_tags",  "biomanufacturing",                                           0.90),
  ("cellculture-br",  "technology_tags","biomanufacturing",                                         0.90),
  ("cellculture-br",  "scale_tags",   "industrial-scale,molecular-scale",                           0.90),
  ("cellmeat-brasil-br","bio_lens_tags","biobased,circular",                                        0.92),
  ("cellmeat-brasil-br","domain_tags", "agri-food,biomanufacturing",                                0.92),
  ("cellmeat-brasil-br","technology_tags","biomanufacturing,fermentation",                          0.92),
  ("cellmeat-brasil-br","scale_tags",  "industrial-scale",                                          0.92),
  ("cellva-ingredients-br","bio_lens_tags","biobased",                                              0.90),
  ("cellva-ingredients-br","domain_tags",  "agri-food,biomanufacturing",                            0.90),
  ("cellva-ingredients-br","technology_tags","precision-fermentation",                              0.90),
  ("cellva-ingredients-br","scale_tags",   "product-scale,industrial-scale",                        0.90),
  ("codebreaker-bioscience-cl","bio_lens_tags","biocentric",                                        0.88),
  ("codebreaker-bioscience-cl","domain_tags",  "agri-food",                                         0.88),
  ("codebreaker-bioscience-cl","technology_tags","ai-data,bioinputs",                               0.88),
  ("codebreaker-bioscience-cl","scale_tags",   "agroecosystem-scale",                               0.88),
  ("consiste-br",     "bio_lens_tags","biobased,circular",                                          0.88),
  ("consiste-br",     "domain_tags",  "agri-food",                                                  0.88),
  ("consiste-br",     "technology_tags","bioinputs",                                                0.88),
  ("consiste-br",     "scale_tags",   "product-scale,industrial-scale",                             0.88),
  ("corpogen-co",     "bio_lens_tags","human-health-bio,biocentric",                                0.88),
  ("corpogen-co",     "domain_tags",  "diagnostics-medtech",                                        0.88),
  ("corpogen-co",     "technology_tags","diagnostics,synthetic-biology",                            0.88),
  ("corpogen-co",     "scale_tags",   "molecular-scale",                                            0.88),
  ("cropguard-cl",    "bio_lens_tags","biocentric,biobased",                                        0.88),
  ("cropguard-cl",    "domain_tags",  "agri-food",                                                  0.88),
  ("cropguard-cl",    "technology_tags","bioinputs",                                                0.88),
  ("cropguard-cl",    "scale_tags",   "agroecosystem-scale",                                        0.88),
  ("devalor-cl",      "bio_lens_tags","biocentric,biobased",                                        0.88),
  ("devalor-cl",      "domain_tags",  "agri-food",                                                  0.88),
  ("devalor-cl",      "technology_tags","bioinputs",                                                0.88),
  ("devalor-cl",      "scale_tags",   "agroecosystem-scale",                                        0.88),
  ("digital-twin-corporation-cr","bio_lens_tags","planetary-boundary",                              0.82),
  ("digital-twin-corporation-cr","domain_tags",  "climate-resource",                                0.82),
  ("digital-twin-corporation-cr","technology_tags","iot,ai-data",                                   0.82),
  ("digital-twin-corporation-cr","scale_tags",   "agroecosystem-scale,territorial-scale",           0.82),
  ("dimitra-bolivia-operations-bo","bio_lens_tags","biocentric",                                    0.80),
  ("dimitra-bolivia-operations-bo","domain_tags",  "agri-food",                                     0.80),
  ("dimitra-bolivia-operations-bo","technology_tags","ai-data,remote-sensing",                      0.80),
  ("dimitra-bolivia-operations-bo","scale_tags",   "agroecosystem-scale,territorial-scale",         0.80),
  ("eatcloud-co",     "bio_lens_tags","circular,planetary-boundary",                                0.82),
  ("eatcloud-co",     "domain_tags",  "agri-food",                                                  0.82),
  ("eatcloud-co",     "technology_tags","ai-data",                                                  0.82),
  ("eatcloud-co",     "scale_tags",   "territorial-scale",                                          0.82),
  ("ecocycle-biotech-ec","bio_lens_tags","biocentric,biobased",                                     0.90),
  ("ecocycle-biotech-ec","domain_tags", "agri-food",                                                0.90),
  ("ecocycle-biotech-ec","technology_tags","bioinputs",                                             0.90),
  ("ecocycle-biotech-ec","scale_tags",  "agroecosystem-scale",                                      0.90),
  ("ecombio-cl",      "bio_lens_tags","biocentric,biobased",                                        0.92),
  ("ecombio-cl",      "domain_tags",  "agri-food",                                                  0.92),
  ("ecombio-cl",      "technology_tags","bioinputs",                                                0.92),
  ("ecombio-cl",      "scale_tags",   "agroecosystem-scale",                                        0.92),
]

with open(out, "a", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    for eid, field, val, conf in batch2:
        w.writerow([eid, "startup_extended", field, val, src, conf, f"swarm_inline_tags {date}"])

total = sum(1 for _ in open(out, encoding="utf-8")) - 1
print(f"Batch 2: {len(batch2)} filas. Total entity_enrichments: {total}")
