"""Batch 6 — 23 startups restantes. Cierra el ciclo de tag population."""
import csv, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
out = ROOT / "staging" / "entity_enrichments.csv"
date = "2026-06-25"
src = "swarm_inline_sonnet_v1"

batch6 = [
  ("agritech-bolivia-bo",     "bio_lens_tags","biocentric",                                         0.78),
  ("agritech-bolivia-bo",     "domain_tags",  "agri-food",                                          0.78),
  ("agritech-bolivia-bo",     "technology_tags","ai-data,iot",                                      0.78),
  ("agritech-bolivia-bo",     "scale_tags",   "agroecosystem-scale",                                0.78),
  ("agricultic-do",           "bio_lens_tags","biocentric",                                         0.75),
  ("agricultic-do",           "domain_tags",  "agri-food",                                          0.75),
  ("agricultic-do",           "technology_tags","ai-data",                                          0.75),
  ("agricultic-do",           "scale_tags",   "agroecosystem-scale",                                0.75),
  ("agrigenetic-ecuador-ec",  "bio_lens_tags","biocentric,biobased",                                0.88),
  ("agrigenetic-ecuador-ec",  "domain_tags",  "agri-food",                                          0.88),
  ("agrigenetic-ecuador-ec",  "technology_tags","synthetic-biology",                                0.88),
  ("agrigenetic-ecuador-ec",  "scale_tags",   "agroecosystem-scale",                                0.88),
  ("agro-logica-co",          "bio_lens_tags","biocentric,biobased",                                0.82),
  ("agro-logica-co",          "domain_tags",  "agri-food",                                          0.82),
  ("agro-logica-co",          "technology_tags","bioinputs",                                        0.82),
  ("agro-logica-co",          "scale_tags",   "agroecosystem-scale",                                0.82),
  ("agro360-do",              "bio_lens_tags","biocentric",                                         0.75),
  ("agro360-do",              "domain_tags",  "agri-food",                                          0.75),
  ("agro360-do",              "technology_tags","ai-data,iot",                                      0.75),
  ("agro360-do",              "scale_tags",   "agroecosystem-scale",                                0.75),
  ("agrocontrol-gt",          "bio_lens_tags","biocentric",                                         0.75),
  ("agrocontrol-gt",          "domain_tags",  "agri-food",                                          0.75),
  ("agrocontrol-gt",          "technology_tags","iot,ai-data",                                      0.75),
  ("agrocontrol-gt",          "scale_tags",   "agroecosystem-scale",                                0.75),
  ("agroguia-ve",             "bio_lens_tags","biocentric",                                         0.78),
  ("agroguia-ve",             "domain_tags",  "agri-food",                                          0.78),
  ("agroguia-ve",             "technology_tags","ai-data",                                          0.78),
  ("agroguia-ve",             "scale_tags",   "agroecosystem-scale",                                0.78),
  ("agroscan-ec",             "bio_lens_tags","biocentric,planetary-boundary",                      0.88),
  ("agroscan-ec",             "domain_tags",  "agri-food",                                          0.88),
  ("agroscan-ec",             "technology_tags","remote-sensing,ai-data",                           0.88),
  ("agroscan-ec",             "scale_tags",   "agroecosystem-scale",                                0.88),
  ("alecrim-biotech-br",      "bio_lens_tags","biobased",                                           0.92),
  ("alecrim-biotech-br",      "domain_tags",  "agri-food,biomanufacturing",                         0.92),
  ("alecrim-biotech-br",      "technology_tags","precision-fermentation",                           0.92),
  ("alecrim-biotech-br",      "scale_tags",   "product-scale,industrial-scale",                     0.92),
  ("aquabio-cl",              "bio_lens_tags","biocentric",                                         0.85),
  ("aquabio-cl",              "domain_tags",  "agri-food",                                          0.85),
  ("aquabio-cl",              "technology_tags","diagnostics,ai-data",                              0.85),
  ("aquabio-cl",              "scale_tags",   "agroecosystem-scale",                                0.85),
  ("ascribe-bio-br",          "bio_lens_tags","biocentric,biobased",                                0.93),
  ("ascribe-bio-br",          "domain_tags",  "agri-food",                                          0.93),
  ("ascribe-bio-br",          "technology_tags","bioinputs",                                        0.93),
  ("ascribe-bio-br",          "scale_tags",   "agroecosystem-scale",                                0.93),
  ("ayni-desert-interaction-cl","bio_lens_tags","biocentric,biobased",                              0.90),
  ("ayni-desert-interaction-cl","domain_tags",  "agri-food",                                        0.90),
  ("ayni-desert-interaction-cl","technology_tags","bioinputs",                                      0.90),
  ("ayni-desert-interaction-cl","scale_tags",   "agroecosystem-scale",                              0.90),
  ("biiosmart-co",            "bio_lens_tags","human-health-bio",                                   0.88),
  ("biiosmart-co",            "domain_tags",  "therapeutics-regenerative",                          0.88),
  ("biiosmart-co",            "technology_tags","therapeutics",                                     0.88),
  ("biiosmart-co",            "scale_tags",   "molecular-scale,human-scale",                        0.88),
  ("biowit-mx",               "bio_lens_tags","human-health-bio",                                   0.90),
  ("biowit-mx",               "domain_tags",  "diagnostics-medtech",                                0.90),
  ("biowit-mx",               "technology_tags","diagnostics",                                      0.90),
  ("biowit-mx",               "scale_tags",   "human-scale,product-scale",                          0.90),
  ("Bee Technology",          "bio_lens_tags","biobased,circular",                                  0.88),
  ("Bee Technology",          "domain_tags",  "agri-food",                                          0.88),
  ("Bee Technology",          "technology_tags","bioinputs,biomaterials",                           0.88),
  ("Bee Technology",          "scale_tags",   "product-scale,agroecosystem-scale",                  0.88),
  ("biocell-mx",              "bio_lens_tags","human-health-bio",                                   0.90),
  ("biocell-mx",              "domain_tags",  "therapeutics-regenerative",                          0.90),
  ("biocell-mx",              "technology_tags","therapeutics",                                     0.90),
  ("biocell-mx",              "scale_tags",   "molecular-scale,human-scale",                        0.90),
  ("biodiverso-insumos-br",   "bio_lens_tags","biocentric,biobased",                                0.90),
  ("biodiverso-insumos-br",   "domain_tags",  "agri-food",                                          0.90),
  ("biodiverso-insumos-br",   "technology_tags","bioinputs",                                        0.90),
  ("biodiverso-insumos-br",   "scale_tags",   "agroecosystem-scale",                                0.90),
  ("biofactory-br",           "bio_lens_tags","biobased,bio-enabled-industrial-transition",         0.85),
  ("biofactory-br",           "domain_tags",  "biomanufacturing",                                   0.85),
  ("biofactory-br",           "technology_tags","biomanufacturing",                                 0.85),
  ("biofactory-br",           "scale_tags",   "industrial-scale",                                   0.85),
  ("biofresh-br",             "bio_lens_tags","biobased,circular",                                  0.85),
  ("biofresh-br",             "domain_tags",  "agri-food",                                          0.85),
  ("biofresh-br",             "technology_tags","bioinputs",                                        0.85),
  ("biofresh-br",             "scale_tags",   "product-scale",                                      0.85),
  ("biohack-uio-ec",          "bio_lens_tags","bio-enabled-industrial-transition",                  0.82),
  ("biohack-uio-ec",          "domain_tags",  "biomanufacturing",                                   0.82),
  ("biohack-uio-ec",          "technology_tags","synthetic-biology",                                0.82),
  ("biohack-uio-ec",          "scale_tags",   "human-scale",                                        0.82),
  ("biolife-innovations-bo",  "bio_lens_tags","biocentric,biobased",                                0.88),
  ("biolife-innovations-bo",  "domain_tags",  "agri-food,climate-resource",                         0.88),
  ("biolife-innovations-bo",  "technology_tags","bioinputs",                                        0.88),
  ("biolife-innovations-bo",  "scale_tags",   "agroecosystem-scale",                                0.88),
  ("biomar-cr",               "bio_lens_tags","biocentric",                                         0.85),
  ("biomar-cr",               "domain_tags",  "agri-food",                                          0.85),
  ("biomar-cr",               "technology_tags","bioinputs",                                        0.85),
  ("biomar-cr",               "scale_tags",   "agroecosystem-scale",                                0.85),
  ("biometrics-medellin-co",  "bio_lens_tags","human-health-bio",                                   0.92),
  ("biometrics-medellin-co",  "domain_tags",  "diagnostics-medtech",                                0.92),
  ("biometrics-medellin-co",  "technology_tags","diagnostics",                                      0.92),
  ("biometrics-medellin-co",  "scale_tags",   "human-scale,product-scale",                          0.92),
]

with open(out, "a", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    for eid, field, val, conf in batch6:
        w.writerow([eid, "startup_extended", field, val, src, conf, f"swarm_inline_tags {date}"])

total = sum(1 for _ in open(out, encoding="utf-8")) - 1
print(f"Batch 6 (final): {len(batch6)} filas. Total entity_enrichments: {total}")
