param(
    [string]$Root = "C:\Users\Pablo A\Documents\Codex\2026-04-18-summarize-what-s-happening-on-slack"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Upsert-CsvById {
    param(
        [string]$Path,
        [object[]]$Rows
    )

    $existing = if (Test-Path -LiteralPath $Path) { Import-Csv -LiteralPath $Path } else { @() }
    $map = @{}
    foreach ($row in $existing) {
        $map[[string]$row.startup_id] = $row
    }
    foreach ($row in $Rows) {
        $map[[string]$row.startup_id] = $row
    }
    $map.Values | Sort-Object startup_name | Export-Csv -LiteralPath $Path -NoTypeInformation -Encoding UTF8
}

$taxonomyRows = @(
    [pscustomobject]@{
        startup_id='cellva'
        startup_name='Cellva'
        macro_theme='food biotech and novel ingredients'
        emergent_theme='food transition ingredients and proteins'
        market_label='microencapsulated functional ingredients'
        technical_stack='microencapsulation; ingredient stabilization; bioactive protection; algae ingredients'
        transition_function='less-stable-food-ingredients-to-bioavailable-clean-label-functional-ingredients'
        output_class='functional ingredient platform'
        feedstock='algae ingredients, coffee-derived ingredients and bioactives'
        industry_destination='food and beverage'
        market_interface='ingredient company'
        scope_decision='include'
        scope_reason='official_site_signal_bio_based_or_biocentric'
        scope_source='cellva_official_site'
        evidence_source='cellva_official_site_2026'
        notes='Official site describes a new generation of ingredients delivered through proprietary microencapsulation technology, including microencapsulated omega-3 from algae and other clean-label ingredient solutions.'
        confidence='0.87'
    }
    [pscustomobject]@{
        startup_id='done_properly'
        startup_name='Done Properly'
        macro_theme='food biotech and novel ingredients'
        emergent_theme='food transition ingredients and proteins'
        market_label='fermented sustainable food ingredients'
        technical_stack='fermentation; mycoprotein; flavor modulation; food biotech'
        transition_function='less-sustainable-food-formulation-to-fermented-bioingredients'
        output_class='food ingredient platform'
        feedstock='microbial fermentation and mycelium-based food ingredients'
        industry_destination='food industry'
        market_interface='ingredient company'
        scope_decision='include'
        scope_reason='official_site_signal_bio_based_or_biocentric'
        scope_source='done_properly_official_site'
        evidence_source='done_properly_official_site_2026'
        notes='Official site says the company ferments sustainable solutions to restore balance with nature and creates healthy, sustainable and tasty bio-ingredients through fermentation technology.'
        confidence='0.90'
    }
    [pscustomobject]@{
        startup_id='fungi_life'
        startup_name='Fungi Life'
        macro_theme='biobased chemistry and advanced materials'
        emergent_theme='biobased chemistry and materials'
        market_label='fungal biosurfactants platform'
        technical_stack='fungal biotechnology; sophorolipids; fermentation; circular biosurfactants'
        transition_function='petroleum-derived-surfactants-to-biodegradable-fungal-biosurfactants'
        output_class='biobased chemical platform'
        feedstock='fungal fermentation and biosurfactant production'
        industry_destination='cleaning, cosmetics, agriculture, oil and gas and bioremediation'
        market_interface='industrial ingredient company'
        scope_decision='include'
        scope_reason='official_site_signal_bio_based_or_biocentric'
        scope_source='fungi_life_official_site'
        evidence_source='fungi_life_official_site_2026'
        notes='Official site describes replacing petroleum-derived surfactants with fungal biotech ingredients and producing high-performance sophorolipids in a scalable process.'
        confidence='0.90'
    }
    [pscustomobject]@{
        startup_id='wiagro'
        startup_name='Wiagro'
        macro_theme='precision agriculture and resource intelligence'
        emergent_theme='precision agriculture intelligence'
        market_label='post-harvest grain monitoring and traceability'
        technical_stack='sensors; satellite connectivity; predictive models; traceability platform; blockchain'
        transition_function='post-harvest-loss-and-low-visibility-to-real-time-grain-monitoring'
        output_class='ag intelligence platform'
        feedstock='stored grain monitoring data'
        industry_destination='agriculture and grain supply chains'
        market_interface='B2B platform'
        scope_decision='include'
        scope_reason='official_site_signal_material_ag_system'
        scope_source='wiagro_official_site'
        evidence_source='wiagro_official_site_2026'
        notes='Official site describes Smart Silobag as a platform combining sensor data, environmental information and predictive models to prevent post-harvest loss and improve traceability and proof of origin.'
        confidence='0.88'
    }
    [pscustomobject]@{
        startup_id='zoomagri'
        startup_name='ZoomAgri'
        macro_theme='precision agriculture and resource intelligence'
        emergent_theme='precision agriculture intelligence'
        market_label='agri commodity inspection intelligence'
        technical_stack='computer vision; machine learning; digital inspection and certification'
        transition_function='manual-subjective-inspection-to-digital-objective-agri-certification'
        output_class='ag intelligence platform'
        feedstock='agri commodity image and inspection data'
        industry_destination='agri commodities and food supply chains'
        market_interface='B2B platform'
        scope_decision='include'
        scope_reason='official_site_signal_material_ag_system'
        scope_source='zoomagri_official_site'
        evidence_source='zoomagri_official_site_2026'
        notes='Official site describes a global agtech company transforming testing, inspection and certification of agri commodities and food via computer vision and machine learning.'
        confidence='0.89'
    }
    [pscustomobject]@{
        startup_id='biosynaptica'
        startup_name='BioSynaptica'
        macro_theme='therapeutics and regenerative medicine'
        emergent_theme='therapeutic and regenerative biology'
        market_label='neurodegenerative biopharmaceuticals'
        technical_stack='biopharmaceutical development; hEPO derivatives; neuroprotective therapeutics'
        transition_function='limited-neurodegenerative-treatment-to-innovative-biopharmaceuticals'
        output_class='therapeutic platform'
        feedstock='human erythropoietin derivatives and neurodegenerative disease biology'
        industry_destination='therapeutics'
        market_interface='therapeutic company'
        scope_decision='include'
        scope_reason='official_site_signal_bio_based_or_biocentric'
        scope_source='biosynaptica_official_site'
        evidence_source='biosynaptica_official_site_2026'
        notes='Official site describes innovative biopharmaceuticals for neurodegenerative diseases based on human erythropoietin derivatives.'
        confidence='0.91'
    }
    [pscustomobject]@{
        startup_id='semion'
        startup_name='Semion'
        macro_theme='ag biologicals and crop resilience'
        emergent_theme='ag biologicals and crop resilience'
        market_label='plant defense activation biotech'
        technical_stack='crop defense activation; biomimicry; plant resilience biology'
        transition_function='pest-vulnerable-crops-to-activated-natural-defense-mechanisms'
        output_class='ag biological platform'
        feedstock='plant defense pathways and crop resilience biology'
        industry_destination='agriculture'
        market_interface='ag biotech company'
        scope_decision='include'
        scope_reason='official_site_signal_bio_based_or_biocentric'
        scope_source='semion_official_site'
        evidence_source='semion_official_site_2026'
        notes='Official site says Semion makes plants defend themselves by restoring natural defense mechanisms lost during domestication and activating plant defenses without genetic modification.'
        confidence='0.92'
    }
    [pscustomobject]@{
        startup_id='dprotein'
        startup_name='DProtein'
        macro_theme='food biotech and novel ingredients'
        emergent_theme='food transition ingredients and proteins'
        market_label='sustainable engineered proteins'
        technical_stack='computational biology; cell engineering; precision fermentation'
        transition_function='animal-and-plant-protein-dependence-to-engineered-sustainable-proteins'
        output_class='protein ingredient platform'
        feedstock='engineered bacterial production systems'
        industry_destination='food and beverage'
        market_interface='ingredient company'
        scope_decision='include'
        scope_reason='external_profile_signal_bio_based_or_biocentric'
        scope_source='dprotein_linkedin_official'
        evidence_source='dprotein_linkedin_2026'
        notes='LinkedIn company page describes sustainable proteins produced without the need of plants or animals, using computational biology, cell engineering and fermentation-related methods.'
        confidence='0.78'
    }
    [pscustomobject]@{
        startup_id='zavia_bio'
        startup_name='Zavia Bio'
        macro_theme='ag biologicals and crop resilience'
        emergent_theme='ag biologicals and crop resilience'
        market_label='agricultural biosolutions for resilience'
        technical_stack='biological solutions; agricultural biotechnology'
        transition_function='less-resilient-farming-to-biological-solutions-for-sustainable-agriculture'
        output_class='ag biological platform'
        feedstock='agricultural biological systems'
        industry_destination='agriculture'
        market_interface='ag biotech company'
        scope_decision='include'
        scope_reason='external_profile_signal_bio_based_or_biocentric'
        scope_source='zavia_bio_linkedin_official'
        evidence_source='zavia_bio_linkedin_2026'
        notes='LinkedIn company page describes biosolutions for resilient and sustainable agriculture and biological solutions for a more sustainable, resilient and safe agricultural system.'
        confidence='0.79'
    }
)

$profileRows = @(
    [pscustomobject]@{
        startup_id='cellva'
        startup_name='Cellva'
        startup_summary_v1='Startup de ingredientes funcionales que usa microencapsulacion propietaria para mejorar estabilidad, biodisponibilidad y funcionalidad de ingredientes alimentarios, incluyendo omega-3 de algas. Entra en tesis por food biotech and novel ingredients.'
        business_one_liner='Microencapsulated functional ingredients for food and beverage.'
        problem_addressed='Ingredientes funcionales con baja estabilidad, menor biodisponibilidad o peor desempeno formulativo.'
        technical_approach='Microencapsulacion para proteger bioactivos, mejorar entrega de nutrientes y habilitar ingredientes clean-label.'
        industry_destination='Food and beverage'
        materiality_signal='high'
        thesis_scope_note='Entra por ingredientes claramente biobasados y por su interfaz directa con formulacion alimentaria.'
        source_url='https://cellva.com/'
        source_type='official_website'
        source_date='2026-04-21'
        evidence_excerpt='Official site describes a new generation of ingredients delivered through proprietary microencapsulation technology, including microencapsulated omega-3 from algae.'
        summary_confidence='high'
        review_status='reviewed'
    }
    [pscustomobject]@{
        startup_id='done_properly'
        startup_name='Done Properly'
        startup_summary_v1='Startup food biotech que desarrolla bioingredientes sustentables por fermentacion, incluyendo proteina de micelio y moduladores naturales de sabor. Entra en tesis por food biotech and novel ingredients.'
        business_one_liner='Fermented sustainable bio-ingredients for the food industry.'
        problem_addressed='Necesidad de ingredientes alimentarios mas saludables, sostenibles y sabrosos con menor carga ambiental.'
        technical_approach='Fermentacion y ciencia del sabor para desarrollar ingredientes de micelio y extractos funcionales.'
        industry_destination='Food industry'
        materiality_signal='high'
        thesis_scope_note='Entra por biotecnologia alimentaria clara, ingrediente biobasado y reemplazo material dentro del sistema alimentario.'
        source_url='https://www.doneproperly.co/'
        source_type='official_website'
        source_date='2026-04-21'
        evidence_excerpt='Official site says it ferments sustainable solutions to restore balance with nature and creates healthy, sustainable and tasty bio-ingredients through fermentation technology.'
        summary_confidence='high'
        review_status='reviewed'
    }
    [pscustomobject]@{
        startup_id='fungi_life'
        startup_name='Fungi Life'
        startup_summary_v1='Startup biotech que reemplaza surfactantes sinteticos derivados del petroleo por biosurfactantes de origen fungico obtenidos por fermentacion. Entra en tesis por biobased chemistry and advanced materials.'
        business_one_liner='Fungal biosurfactants to replace petroleum-derived surfactants.'
        problem_addressed='Dependencia de surfactantes toxicos y no biodegradables derivados del petroleo.'
        technical_approach='Produccion escalable de sophorolipidos y otros biosurfactantes via biotecnologia fungica.'
        industry_destination='Cleaning, cosmetics, agriculture, oil and gas and bioremediation'
        materiality_signal='high'
        thesis_scope_note='Entra por sustitucion material clara y por quimica biobasada con impacto fuerte sobre limites planetarios.'
        source_url='https://www.fungilife.net/'
        source_type='official_website'
        source_date='2026-04-21'
        evidence_excerpt='Official site describes replacing synthetic petroleum-derived surfactants with ingredients obtained from fungal biotechnology and producing sophorolipids in a scalable process.'
        summary_confidence='high'
        review_status='reviewed'
    }
    [pscustomobject]@{
        startup_id='wiagro'
        startup_name='Wiagro'
        startup_summary_v1='Startup agtech que monitorea granos almacenados y silobolsas con sensores, conectividad satelital, modelos predictivos y trazabilidad digital para evitar perdidas postcosecha. Entra en tesis por precision agriculture and resource intelligence.'
        business_one_liner='Post-harvest grain monitoring and traceability platform.'
        problem_addressed='Perdidas postcosecha, baja visibilidad sobre calidad de grano almacenado y trazabilidad limitada.'
        technical_approach='Sensores, datos ambientales, modelos predictivos, conectividad satelital y plataforma web/mobile para monitoreo de granos.'
        industry_destination='Agriculture and grain supply chains'
        materiality_signal='high'
        thesis_scope_note='Entra por fuerte acople a flujos materiales de granos y por reducir perdidas reales del sistema agroalimentario.'
        source_url='https://www.wiagro.com/'
        source_type='official_website'
        source_date='2026-04-21'
        evidence_excerpt='Official site says Smart Silobag combines sensor data, environmental information and predictive models to prevent post-harvest loss, improve traceability and provide proof of origin.'
        summary_confidence='high'
        review_status='reviewed'
    }
    [pscustomobject]@{
        startup_id='zoomagri'
        startup_name='ZoomAgri'
        startup_summary_v1='Startup agtech que digitaliza inspeccion, testeo y certificacion de commodities agricolas y alimentos mediante computer vision y machine learning. Entra en tesis por precision agriculture and resource intelligence.'
        business_one_liner='Computer-vision inspection and certification for agri commodities and food.'
        problem_addressed='Procesos de inspeccion y certificacion mas manuales, lentos o subjetivos en cadenas agroindustriales.'
        technical_approach='Reconocimiento varietal y analisis de calidad mediante computer vision y machine learning.'
        industry_destination='Agri commodities and food supply chains'
        materiality_signal='high'
        thesis_scope_note='Entra como infraestructura de inteligencia material para commodities y alimentos, no como software horizontal.'
        source_url='https://zoomagri.com/en/home/'
        source_type='official_website'
        source_date='2026-04-21'
        evidence_excerpt='Official site says ZoomAgri is transforming testing, inspection and certification of agri commodities and food via computer vision and machine learning.'
        summary_confidence='high'
        review_status='reviewed'
    }
    [pscustomobject]@{
        startup_id='biosynaptica'
        startup_name='BioSynaptica'
        startup_summary_v1='Startup biotecnologica que desarrolla biofarmacos innovadores para enfermedades neurodegenerativas a partir de derivados de eritropoyetina humana. Entra en tesis por therapeutics and regenerative medicine.'
        business_one_liner='Innovative biopharmaceuticals for neurodegenerative diseases.'
        problem_addressed='Ausencia de tratamientos efectivos que prevengan o curen enfermedades neurodegenerativas.'
        technical_approach='Desarrollo de neurofarmacos basados en variantes derivadas de eritropoyetina humana con funcion neuroprotectora.'
        industry_destination='Therapeutics'
        materiality_signal='high'
        thesis_scope_note='Entra por biologia terapeutica clara y porque su actividad no es software sino biofarmaceutica.'
        source_url='https://biosynaptica.com/'
        source_type='official_website'
        source_date='2026-04-21'
        evidence_excerpt='Official site says BioSynaptica develops innovative biopharmaceuticals for neurodegenerative diseases and focuses on a neuropharmaceutical based on human erythropoietin derivatives.'
        summary_confidence='high'
        review_status='reviewed'
    }
    [pscustomobject]@{
        startup_id='semion'
        startup_name='Semion'
        startup_summary_v1='Startup agrobiotech que activa mecanismos naturales de defensa de las plantas perdidos durante la domesticacion para mejorar resiliencia frente a plagas sin modificar geneticamente los cultivos. Entra en tesis por ag biologicals and crop resilience.'
        business_one_liner='Biotech to activate natural plant defenses.'
        problem_addressed='Cultivos domesticados con defensas naturales silenciadas y mayor vulnerabilidad frente a plagas.'
        technical_approach='Biomimesis de defensas de plantas silvestres para activar mecanismos que no se expresan bajo ataque.'
        industry_destination='Agriculture'
        materiality_signal='high'
        thesis_scope_note='Entra por acople biologico directo con cultivos y resiliencia agroecologica, ademas de ser un buen caso biocentrico.'
        source_url='https://semionbio.com/'
        source_type='official_website'
        source_date='2026-04-21'
        evidence_excerpt='Official site says Semion restores natural defense mechanisms lost during domestication and develops targeted solutions to activate plant defenses instead of killing pests or using GM.'
        summary_confidence='high'
        review_status='reviewed'
    }
    [pscustomobject]@{
        startup_id='dprotein'
        startup_name='DProtein'
        startup_summary_v1='Startup food biotech que diseña proteinas nutricionales y sostenibles sin depender de plantas ni animales, usando biologia computacional, ingenieria celular y fermentacion. Entra en tesis por food biotech and novel ingredients.'
        business_one_liner='Engineered sustainable proteins without plants or animals.'
        problem_addressed='Dependencia de proteinas con mayor huella material o menor optimizacion nutricional.'
        technical_approach='Diseno de novo de proteinas y produccion mediante sistemas celulares e ingenieria biologica.'
        industry_destination='Food and beverage'
        materiality_signal='high'
        thesis_scope_note='Entra por transicion proteica y por producir ingredientes proteicos sostenibles desde biologia diseñada.'
        source_url='https://www.linkedin.com/company/dprotein'
        source_type='linkedin_company_page'
        source_date='2026-04-21'
        evidence_excerpt='LinkedIn company page says DProtein produces nutritionally optimized and sustainable proteins without the need of plants or animals, and describes its first product as a complete vegan protein.'
        summary_confidence='medium'
        review_status='seeded'
    }
    [pscustomobject]@{
        startup_id='zavia_bio'
        startup_name='Zavia Bio'
        startup_summary_v1='Startup agrobiotech que desarrolla soluciones biologicas para un sistema agricola mas sostenible, resiliente y seguro. Entra en tesis por ag biologicals and crop resilience.'
        business_one_liner='Biosolutions for resilient and sustainable agriculture.'
        problem_addressed='Necesidad de sistemas agricolas mas resilientes y sostenibles.'
        technical_approach='Desarrollo de soluciones biologicas para agricultura desde una plataforma biotech interdisciplinaria.'
        industry_destination='Agriculture'
        materiality_signal='high'
        thesis_scope_note='Entra como plataforma de biosoluciones aplicadas a agricultura y resiliencia del sistema vivo.'
        source_url='https://ar.linkedin.com/company/zaviabio'
        source_type='linkedin_company_page'
        source_date='2026-04-21'
        evidence_excerpt='LinkedIn company page describes biosolutions for resilient and sustainable agriculture and biological solutions for a more sustainable, resilient and safe agricultural system.'
        summary_confidence='medium'
        review_status='seeded'
    }
)

Upsert-CsvById -Path (Join-Path $Root 'quality\manual_startup_taxonomy_overrides.csv') -Rows $taxonomyRows
Upsert-CsvById -Path (Join-Path $Root 'quality\manual_startup_profile_overrides.csv') -Rows $profileRows

Write-Output "Direct Google batch sweep applied."
