param(
    [string]$Root = "C:\Users\Pablo A\Documents\Codex\2026-04-18-summarize-what-s-happening-on-slack"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Upsert-CsvById {
    param(
        [string]$Path,
        [object[]]$Rows
    )

    $existing = if (Test-Path -LiteralPath $Path) { Import-Csv -LiteralPath $Path } else { @() }
    $map = @{}
    foreach ($row in $existing) {
        $map[[string]$row.startup_id] = $row
    }
    foreach ($row in $Rows) {
        $map[[string]$row.startup_id] = $row
    }
    $map.Values | Sort-Object startup_name | Export-Csv -LiteralPath $Path -NoTypeInformation -Encoding UTF8
}

function Upsert-AliasRows {
    param(
        [string]$Path,
        [object[]]$Rows
    )

    $existing = if (Test-Path -LiteralPath $Path) { Import-Csv -LiteralPath $Path } else { @() }
    $map = @{}
    foreach ($row in $existing) {
        $key = ([string]$row.canonical_name + '||' + [string]$row.alias_name)
        $map[$key] = $row
    }
    foreach ($row in $Rows) {
        $key = ([string]$row.canonical_name + '||' + [string]$row.alias_name)
        $map[$key] = $row
    }
    $map.Values | Sort-Object canonical_name, alias_name | Export-Csv -LiteralPath $Path -NoTypeInformation -Encoding UTF8
}

$aliasRows = @(
    [pscustomobject]@{ canonical_name = 'BioCl'; alias_name = 'BioClé'; reason = 'portfolio_name_variant'; confidence = 'high' }
    [pscustomobject]@{ canonical_name = 'Feedvax'; alias_name = 'FeedVax'; reason = 'portfolio_name_variant'; confidence = 'high' }
    [pscustomobject]@{ canonical_name = 'Tomorrow Foods'; alias_name = 'Tomorrow'; reason = 'portfolio_name_variant'; confidence = 'high' }
    [pscustomobject]@{ canonical_name = 'Nanogrow Biotech'; alias_name = 'Nanogrow'; reason = 'portfolio_name_variant'; confidence = 'high' }
    [pscustomobject]@{ canonical_name = 'Onco Precision'; alias_name = 'OncoPrecision'; reason = 'portfolio_name_variant'; confidence = 'high' }
    [pscustomobject]@{ canonical_name = 'WerkÃ©nVac'; alias_name = 'Werken Vac'; reason = 'portfolio_name_variant'; confidence = 'medium' }
)

$portfolioUrl = 'https://www.gridexponential.com/portfolio'

$taxonomyRows = @(
    [pscustomobject]@{ startup_id='avatar_medtech'; startup_name='AVaTAR MedTech'; macro_theme='diagnostics and medtech'; emergent_theme='health diagnostics and medtech'; market_label='heart valve reconstruction devices'; technical_stack='cardiovascular devices; surgical reconstruction; medtech'; transition_function='high-risk-or-limited-heart-valve-repair-to-specialized-reconstruction-devices'; output_class='medical device'; feedstock='cardiac surgery and heart valve repair workflows'; industry_destination='cardiovascular surgery and healthcare'; market_interface='device company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes medical devices for heart valve reconstruction.'; confidence='0.79' }
    [pscustomobject]@{ startup_id='biocle'; startup_name='BioCl'; macro_theme='therapeutics and regenerative medicine'; emergent_theme='therapeutic and regenerative biology'; market_label='digestive health delivery platform'; technical_stack='bacterial vesicles; microbiome delivery; therapeutic biotech'; transition_function='imprecise-gut-health-interventions-to-biological-delivery'; output_class='therapeutic platform'; feedstock='bacterial vesicles'; industry_destination='digestive health and therapeutics'; market_interface='therapeutic platform'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes bacterial vesicles for precise and effective delivery in digestive health.'; confidence='0.80' }
    [pscustomobject]@{ startup_id='break_pet'; startup_name='BreakPET'; macro_theme='biobased chemistry and advanced materials'; emergent_theme='biobased chemistry and materials'; market_label='enzymatic plastic circularity'; technical_stack='engineered enzymes; PET recycling; industrial biotech'; transition_function='linear-petrochemical-plastics-to-circular-material-reuse'; output_class='circular materials solution'; feedstock='PET plastic waste'; industry_destination='materials and circular packaging'; market_interface='industrial solution supplier'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes recycling PET using engineered enzymes for circular plastic reuse.'; confidence='0.88' }
    [pscustomobject]@{ startup_id='bybug'; startup_name='ByBug'; macro_theme='biomanufacturing and bioindustrial platforms'; emergent_theme='industrial biotech and molecular tools'; market_label='insect-based therapeutics biomanufacturing'; technical_stack='genetically modified insects; therapeutic manufacturing; biotech production'; transition_function='conventional-biomanufacturing-to-insect-based-production'; output_class='biomanufacturing platform'; feedstock='genetically modified insects'; industry_destination='therapeutics manufacturing'; market_interface='manufacturing platform'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes therapeutics biomanufacturing using genetically modified insects.'; confidence='0.84' }
    [pscustomobject]@{ startup_id='caligenia'; startup_name='Caligenia'; macro_theme='ag biologicals and crop resilience'; emergent_theme='extremophile microbial ag inputs'; market_label='carbon-negative biofertilizers'; technical_stack='waste valorization; biofertilizers; agricultural biotech'; transition_function='waste-and-synthetic-inputs-to-carbon-negative-biofertility'; output_class='biofertilizer'; feedstock='chicken manure'; industry_destination='agriculture'; market_interface='input supplier'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes turning chicken manure into carbon negative biofertilizers.'; confidence='0.85' }
    [pscustomobject]@{ startup_id='cryosmetics'; startup_name='Cryosmetics'; macro_theme='biobased chemistry and advanced materials'; emergent_theme='biobased chemistry and materials'; market_label='microbiome-positive skincare'; technical_stack='natural skincare biotech; skin microbiome formulations'; transition_function='synthetic-personal-care-to-biobased-microbiome-compatible-products'; output_class='biobased formulation'; feedstock='natural skincare compounds'; industry_destination='personal care'; market_interface='product company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes 100% natural skincare products impacting positively on the skin microbiome.'; confidence='0.76' }
    [pscustomobject]@{ startup_id='cyanomin'; startup_name='CyanoMin'; macro_theme='climate, energy and resource systems'; emergent_theme='resource recovery and bioremediation systems'; market_label='brine bioremediation and mineral recovery'; technical_stack='bioremediation; mineral recovery; extremophile process biotech'; transition_function='polluting-brine-management-to-biological-resource-recovery'; output_class='resource recovery platform'; feedstock='hypersaline brines'; industry_destination='mining, water and resource recovery'; market_interface='industrial solution supplier'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes bioremediation of hypersaline brines with mineral recovery.'; confidence='0.82' }
    [pscustomobject]@{ startup_id='dogma_biotech'; startup_name='Dogma Biotech'; macro_theme='therapeutics and regenerative medicine'; emergent_theme='therapeutic and regenerative biology'; market_label='glyco-engineered therapeutics'; technical_stack='AI-discovered sugars; therapeutic optimization; glycobiology'; transition_function='lower-efficacy-therapeutics-to-glyco-optimized-biology'; output_class='therapeutic platform'; feedstock='glycan design workflows'; industry_destination='biotech and therapeutics'; market_interface='therapeutic platform'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes improving therapeutics efficacy by 20X through AI-discovered sugars.'; confidence='0.82' }
    [pscustomobject]@{ startup_id='embryoxite'; startup_name='Embryoxite'; macro_theme='diagnostics and medtech'; emergent_theme='health diagnostics and medtech'; market_label='IVF diagnostics'; technical_stack='non-invasive embryo diagnostics; reproductive medtech'; transition_function='lower-precision-ivf-to-better-outcome-screening'; output_class='diagnostic platform'; feedstock='IVF and embryo assessment workflows'; industry_destination='fertility medicine'; market_interface='diagnostic company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes a non-invasive diagnostic to enhance IVF outcomes.'; confidence='0.81' }
    [pscustomobject]@{ startup_id='enteria'; startup_name='Enteria'; macro_theme='diagnostics and medtech'; emergent_theme='health diagnostics and medtech'; market_label='microbiota diagnostics'; technical_stack='microbiome diagnostics; gut health testing'; transition_function='coarse-gut-health-evaluation-to-microbiota-based-diagnostics'; output_class='diagnostic tool'; feedstock='microbiota and biological samples'; industry_destination='healthcare diagnostics'; market_interface='diagnostic company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes microbiota-based diagnostic tools.'; confidence='0.79' }
    [pscustomobject]@{ startup_id='food4you'; startup_name='Food4You'; macro_theme='food biotech and novel ingredients'; emergent_theme='food transition ingredients and proteins'; market_label='microbial plant-based food enhancers'; technical_stack='beneficial bacteria; food biotech; formulation'; transition_function='lower-performing-plant-based-products-to-biology-enabled-food-quality'; output_class='food ingredient technology'; feedstock='beneficial bacteria combinations'; industry_destination='plant-based food'; market_interface='ingredient supplier'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes unique bacteria combinations that enhance plant-based products.'; confidence='0.82' }
    [pscustomobject]@{ startup_id='future_biome'; startup_name='Future Biome'; macro_theme='food biotech and novel ingredients'; emergent_theme='food transition ingredients and proteins'; market_label='fungi-based precision prebiotics'; technical_stack='fungi; microbiome optimization; precision prebiotics'; transition_function='generic-gut-health-products-to-precision-microbiome-function'; output_class='functional ingredient'; feedstock='fungi-based prebiotic systems'; industry_destination='food, gut health and wellness'; market_interface='ingredient company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes optimizing microbiome function with fungi-based precision prebiotics.'; confidence='0.78' }
    [pscustomobject]@{ startup_id='gisens_biotech'; startup_name='Gisens Biotech'; macro_theme='diagnostics and medtech'; emergent_theme='health diagnostics and medtech'; market_label='nanotech diagnostics'; technical_stack='nanotechnology diagnostics; portable sensors'; transition_function='centralized-low-precision-diagnostics-to-ubiquitous-precision-testing'; output_class='diagnostic device'; feedstock='diagnostic sensing workflows'; industry_destination='healthcare diagnostics'; market_interface='device company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes ultra-precise diagnostics everywhere through the use of nanotechnology.'; confidence='0.82' }
    [pscustomobject]@{ startup_id='microin'; startup_name='MicroIN'; macro_theme='ag biologicals and crop resilience'; emergent_theme='extremophile microbial ag inputs'; market_label='bioinput microencapsulation'; technical_stack='microencapsulation; ag bioinputs; formulation technology'; transition_function='fragile-bioinputs-to-more-effective-agricultural-delivery'; output_class='bioinput technology'; feedstock='bioinput formulations'; industry_destination='agriculture'; market_interface='input platform'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes microencapsulation technology for bioinput innovation.'; confidence='0.80' }
    [pscustomobject]@{ startup_id='new_organs_biotech'; startup_name='New Organs Biotech'; macro_theme='therapeutics and regenerative medicine'; emergent_theme='therapeutic and regenerative biology'; market_label='gene-edited organ regeneration'; technical_stack='gene editing; regenerative medicine; precision medicine'; transition_function='organ-shortage-to-bioengineered-organ-solutions'; output_class='therapeutic platform'; feedstock='gene editing and regenerative biology workflows'; industry_destination='transplant medicine and regenerative health'; market_interface='therapeutic platform'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes combining gene editing with precision medicine to solve organ shortage.'; confidence='0.86' }
    [pscustomobject]@{ startup_id='ubique_bio'; startup_name='Ubique Bio'; macro_theme='diagnostics and medtech'; emergent_theme='health diagnostics and medtech'; market_label='synthetic peptide diagnostics'; technical_stack='synthetic peptides; diagnostics'; transition_function='limited-diagnostic-access-to-anywhere-testing'; output_class='diagnostic platform'; feedstock='synthetic peptides'; industry_destination='healthcare diagnostics'; market_interface='diagnostic company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes diagnostics everywhere with synthetic peptides.'; confidence='0.82' }
    [pscustomobject]@{ startup_id='vexxel_biotech'; startup_name='Vexxel Biotech'; macro_theme='ag biologicals and crop resilience'; emergent_theme='genome-enabled crop resilience'; market_label='protein-based encapsulation for bioinputs'; technical_stack='protein encapsulation; ag biological delivery'; transition_function='less-precise-bioinput-delivery-to-protein-enabled-release'; output_class='bioinput enabling technology'; feedstock='protein encapsulation systems'; industry_destination='agricultural bioinputs'; market_interface='input technology provider'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes smart, protein-based encapsulation enabling nature to decide.'; confidence='0.78' }
    [pscustomobject]@{ startup_id='zev_biotech'; startup_name='ZEV Biotech'; macro_theme='diagnostics and medtech'; emergent_theme='health diagnostics and medtech'; market_label='distributed molecular diagnostics'; technical_stack='molecular diagnostics; lab-deployable platform'; transition_function='centralized-testing-to-any-lab-diagnostics'; output_class='diagnostic platform'; feedstock='molecular diagnostic workflows'; industry_destination='healthcare and labs'; market_interface='diagnostic company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='gridx_portfolio_official'; evidence_source='gridx_portfolio_2026'; notes='GRIDX portfolio describes a molecular diagnostics platform that can be placed in any lab in the world.'; confidence='0.82' }
)

$profileRows = @(
    [pscustomobject]@{ startup_id='avatar_medtech'; startup_name='AVaTAR MedTech'; startup_summary_v1='Startup medtech que desarrolla dispositivos para reconstruccion de valvulas cardiacas. Entra en tesis por diagnostics and medtech.'; business_one_liner='Heart valve reconstruction devices.'; problem_addressed='Opciones limitadas y procedimientos complejos para reparar valvulas cardiacas.'; technical_approach='Dispositivos medicos orientados a reconstruccion valvular cardiaca.'; industry_destination='Cardiovascular surgery and healthcare'; materiality_signal='high'; thesis_scope_note='Entra por medtech clinico concreto y de alta materialidad biologica.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes medical devices for heart valve reconstruction.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='biocle'; startup_name='BioCl'; startup_summary_v1='Startup biotech que usa vesiculas bacterianas para mejorar delivery preciso en salud digestiva. Entra en tesis por therapeutics and regenerative medicine.'; business_one_liner='Bacterial vesicles for digestive health delivery.'; problem_addressed='Intervenciones poco precisas y menos efectivas en salud digestiva.'; technical_approach='Uso de vesiculas bacterianas como sistema de entrega biologico.'; industry_destination='Digestive health and therapeutics'; materiality_signal='high'; thesis_scope_note='Entra por plataforma terapeutica biologica, no por software.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes bacterial vesicles to transform digestive health through precise and effective delivery.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='break_pet'; startup_name='BreakPET'; startup_summary_v1='Startup de circularidad de materiales que recicla PET con enzimas ingenierizadas. Entra en tesis por biobased chemistry and advanced materials.'; business_one_liner='Enzymatic PET recycling platform.'; problem_addressed='Uso lineal de plasticos petroquimicos y baja circularidad del PET.'; technical_approach='Enzimas ingenierizadas para reciclar PET y habilitar reuso circular.'; industry_destination='Materials and circular packaging'; materiality_signal='high'; thesis_scope_note='Entra por transicion material clara desde plastico lineal a reutilizacion circular.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes recycling PET using engineered enzymes for circular plastic reuse.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='bybug'; startup_name='ByBug'; startup_summary_v1='Startup biotech que usa insectos geneticamente modificados para biomanufactura terapeutica. Entra en tesis por biomanufacturing and bioindustrial platforms.'; business_one_liner='Therapeutics manufacturing with engineered insects.'; problem_addressed='Costos y limitaciones de escalado en biomanufactura terapeutica convencional.'; technical_approach='Uso de insectos geneticamente modificados como plataforma productiva.'; industry_destination='Therapeutics manufacturing'; materiality_signal='high'; thesis_scope_note='Entra por plataforma de manufactura biologica no convencional.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes therapeutics biomanufacturing using genetically modified insects.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='caligenia'; startup_name='Caligenia'; startup_summary_v1='Startup agrobiotech que transforma guano de pollo en biofertilizantes carbono-negativos. Entra en tesis por ag biologicals and crop resilience.'; business_one_liner='Carbon-negative biofertilizers from chicken manure.'; problem_addressed='Residuos pecuarios contaminantes y dependencia de fertilizacion menos regenerativa.'; technical_approach='Valorizacion biologica de guano de pollo para producir biofertilizantes.'; industry_destination='Agriculture'; materiality_signal='high'; thesis_scope_note='Entra por bioinsumos y regeneracion material del sistema agricola.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes turning chicken manure into carbon negative biofertilizers.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='cryosmetics'; startup_name='Cryosmetics'; startup_summary_v1='Startup de personal care biobasado con productos naturales que impactan positivamente el microbioma de la piel. Entra en tesis por biobased chemistry and advanced materials.'; business_one_liner='Natural microbiome-positive skincare.'; problem_addressed='Cuidado de la piel dependiente de formulaciones menos compatibles con microbioma y con mayor carga sintetica.'; technical_approach='Desarrollo de productos de skincare 100% naturales con impacto positivo en el microbioma cutaneo.'; industry_destination='Personal care'; materiality_signal='medium'; thesis_scope_note='Entra por formulacion biobasada y microbioma, aunque mas periferica que otras biotech core.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes 100% natural skincare products impacting positively on the skin microbiome.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='cyanomin'; startup_name='CyanoMin'; startup_summary_v1='Startup de bioremediacion que trata salmueras hipersalinas y recupera minerales. Entra en tesis por climate, energy and resource systems.'; business_one_liner='Bioremediation and mineral recovery platform.'; problem_addressed='Manejo contaminante de salmueras y baja recuperacion de valor mineral.'; technical_approach='Procesos biologicos para remediar salmueras hipersalinas y recuperar minerales.'; industry_destination='Mining, water and resource recovery'; materiality_signal='high'; thesis_scope_note='Entra por restauracion y circularidad de flujos materiales criticos.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes bioremediation of hypersaline brines with mineral recovery.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='dogma_biotech'; startup_name='Dogma Biotech'; startup_summary_v1='Startup therapeutics que usa IA y azucares descubiertos computacionalmente para mejorar la eficacia de tratamientos biologicos. Entra en tesis por therapeutics and regenerative medicine.'; business_one_liner='AI-discovered sugars for better therapeutics.'; problem_addressed='Baja eficacia y optimizacion lenta en terapias biologicas.'; technical_approach='Descubrimiento de azucares y diseno terapeutico asistido por IA.'; industry_destination='Biotech and therapeutics'; materiality_signal='high'; thesis_scope_note='Entra por plataforma terapeutica biologica, no por IA horizontal.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes improving therapeutics efficacy by 20X through AI-discovered sugars.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='embryoxite'; startup_name='Embryoxite'; startup_summary_v1='Startup medtech con diagnostico no invasivo para mejorar resultados en IVF. Entra en tesis por diagnostics and medtech.'; business_one_liner='Non-invasive IVF diagnostic.'; problem_addressed='Menor precision y resultados suboptimos en tratamientos de fertilidad.'; technical_approach='Herramienta diagnostica no invasiva para apoyar decisiones en fertilizacion in vitro.'; industry_destination='Fertility medicine'; materiality_signal='high'; thesis_scope_note='Entra por diagnostica clinica clara y directamente biologica.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes a non-invasive diagnostic to enhance IVF outcomes.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='enteria'; startup_name='Enteria'; startup_summary_v1='Startup que desarrolla herramientas diagnosticas basadas en microbiota. Entra en tesis por diagnostics and medtech.'; business_one_liner='Microbiota-based diagnostics.'; problem_addressed='Falta de diagnosticos mas precisos para condiciones relacionadas con microbiota.'; technical_approach='Herramientas diagnosticas apoyadas en analisis de microbiota.'; industry_destination='Healthcare diagnostics'; materiality_signal='high'; thesis_scope_note='Entra por diagnostica biologica basada en microbiota.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes developing microbiota-based diagnostic tools.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='food4you'; startup_name='Food4You'; startup_summary_v1='Startup food biotech que usa combinaciones bacterianas para mejorar productos plant-based. Entra en tesis por food biotech and novel ingredients.'; business_one_liner='Bacteria-enabled plant-based food enhancement.'; problem_addressed='Bajo desempeno sensorial o funcional de productos plant-based.'; technical_approach='Combinaciones unicas de bacterias para mejorar formulaciones basadas en plantas.'; industry_destination='Plant-based food'; materiality_signal='high'; thesis_scope_note='Entra por fermentacion/microbiologia aplicada a alimentos.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes unique bacteria combinations that enhance plant-based products.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='future_biome'; startup_name='Future Biome'; startup_summary_v1='Startup que desarrolla precision prebiotics basados en hongos para optimizar la funcion del microbioma. Entra en tesis por food biotech and novel ingredients.'; business_one_liner='Fungi-based precision prebiotics.'; problem_addressed='Intervenciones poco precisas sobre la funcion del microbioma.'; technical_approach='Uso de hongos y precision prebiotics para modular el microbioma.'; industry_destination='Food, gut health and wellness'; materiality_signal='medium'; thesis_scope_note='Entra por interfaz clara con microbioma y alimentos/ingredientes funcionales.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes optimizing microbiome function with fungi-based precision prebiotics.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='gisens_biotech'; startup_name='Gisens Biotech'; startup_summary_v1='Startup de nanotech diagnostics que busca llevar diagnostico ultra-preciso a cualquier lugar. Entra en tesis por diagnostics and medtech.'; business_one_liner='Nanotechnology diagnostics everywhere.'; problem_addressed='Acceso limitado a diagnosticos precisos fuera de entornos especializados.'; technical_approach='Uso de nanotecnologia para plataformas diagnosticas ultra-precisas.'; industry_destination='Healthcare diagnostics'; materiality_signal='high'; thesis_scope_note='Entra por diagnostica y nanotecnologia aplicada a biomedicina.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes ultra-precise diagnostics everywhere through the use of nanotechnology.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='microin'; startup_name='MicroIN'; startup_summary_v1='Startup de formulacion que desarrolla microencapsulacion para innovacion en bioinsumos. Entra en tesis por ag biologicals and crop resilience.'; business_one_liner='Microencapsulation for bioinputs.'; problem_addressed='Baja estabilidad y performance de bioinsumos en condiciones reales de uso.'; technical_approach='Tecnologia de microencapsulacion para mejorar entrega y estabilidad de bioinsumos.'; industry_destination='Agriculture'; materiality_signal='high'; thesis_scope_note='Entra como tecnologia habilitante de bioinsumos y resiliencia de cultivos.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes microencapsulation technology for bioinput innovation.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='new_organs_biotech'; startup_name='New Organs Biotech'; startup_summary_v1='Startup de medicina regenerativa que combina gene editing y precision medicine para enfrentar la escasez de organos. Entra en tesis por therapeutics and regenerative medicine.'; business_one_liner='Gene-edited regenerative medicine for organ shortage.'; problem_addressed='Escasez cronica de organos y limites de las soluciones convencionales de trasplante.'; technical_approach='Combinacion de edicion genetica y precision medicine para nuevas soluciones organicas.'; industry_destination='Transplant medicine and regenerative health'; materiality_signal='high'; thesis_scope_note='Entra por medicina regenerativa profunda y biologia aplicada.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes combining gene-editing with precision medicine to solve organ shortage.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='ubique_bio'; startup_name='Ubique Bio'; startup_summary_v1='Startup de diagnostico que usa peptidos sinteticos para habilitar testing distribuido. Entra en tesis por diagnostics and medtech.'; business_one_liner='Diagnostics with synthetic peptides.'; problem_addressed='Acceso limitado a diagnosticos robustos fuera de laboratorios centrales.'; technical_approach='Plataforma diagnostica basada en peptidos sinteticos.'; industry_destination='Healthcare diagnostics'; materiality_signal='high'; thesis_scope_note='Entra por diagnostica biologica concreta.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes diagnostics everywhere with synthetic peptides.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='vexxel_biotech'; startup_name='Vexxel Biotech'; startup_summary_v1='Startup de encapsulacion proteica inteligente para bioinsumos y decisiones biologicas mas precisas. Entra en tesis por ag biologicals and crop resilience.'; business_one_liner='Smart protein-based encapsulation.'; problem_addressed='Entrega suboptima de bioinsumos y menor precision en sistemas biologicos aplicados al agro.'; technical_approach='Encapsulacion basada en proteinas para controlar liberacion y desempeno de soluciones biologicas.'; industry_destination='Agricultural bioinputs'; materiality_signal='high'; thesis_scope_note='Entra como tecnologia habilitante de bioinsumos y agricultura regenerativa.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes smart, protein-based encapsulation enabling nature to decide.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='zev_biotech'; startup_name='ZEV Biotech'; startup_summary_v1='Startup de molecular diagnostics con plataforma que puede instalarse en cualquier laboratorio. Entra en tesis por diagnostics and medtech.'; business_one_liner='Lab-deployable molecular diagnostics platform.'; problem_addressed='Baja disponibilidad de plataformas diagnosticas moleculares flexibles a escala global.'; technical_approach='Plataforma molecular de diagnostico desplegable en laboratorios distribuidos.'; industry_destination='Healthcare and labs'; materiality_signal='high'; thesis_scope_note='Entra por diagnostica molecular clara.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='GRIDX portfolio describes a molecular diagnostics platform that can be placed in any lab in the world.'; summary_confidence='medium'; review_status='seeded' }
)

Upsert-AliasRows -Path (Join-Path $Root 'staging\manual_alias_overrides.csv') -Rows $aliasRows
Upsert-CsvById -Path (Join-Path $Root 'quality\manual_startup_taxonomy_overrides.csv') -Rows $taxonomyRows
Upsert-CsvById -Path (Join-Path $Root 'quality\manual_startup_profile_overrides.csv') -Rows $profileRows

Write-Output "GRIDX portfolio sweep applied."
