param(
    [string]$Root = "C:\Users\Pablo A\Documents\Codex\2026-04-18-summarize-what-s-happening-on-slack"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Upsert-CsvById {
    param(
        [string]$Path,
        [object[]]$Rows
    )

    $existing = if (Test-Path -LiteralPath $Path) { Import-Csv -LiteralPath $Path } else { @() }
    $map = @{}
    foreach ($row in $existing) {
        $map[[string]$row.startup_id] = $row
    }
    foreach ($row in $Rows) {
        $map[[string]$row.startup_id] = $row
    }
    $map.Values | Sort-Object startup_name | Export-Csv -LiteralPath $Path -NoTypeInformation -Encoding UTF8
}

function Upsert-AliasRows {
    param(
        [string]$Path,
        [object[]]$Rows
    )

    $existing = if (Test-Path -LiteralPath $Path) { Import-Csv -LiteralPath $Path } else { @() }
    $map = @{}
    foreach ($row in $existing) {
        $key = ([string]$row.canonical_name + '||' + [string]$row.alias_name)
        $map[$key] = $row
    }
    foreach ($row in $Rows) {
        $key = ([string]$row.canonical_name + '||' + [string]$row.alias_name)
        $map[$key] = $row
    }
    $map.Values | Sort-Object canonical_name, alias_name | Export-Csv -LiteralPath $Path -NoTypeInformation -Encoding UTF8
}

$portfolioUrl = 'https://sf500.com.ar/'

$aliasRows = @(
    [pscustomobject]@{ canonical_name = 'Unibaio'; alias_name = 'UNIBAIO'; reason = 'portfolio_name_variant'; confidence = 'high' }
    [pscustomobject]@{ canonical_name = 'Eirú'; alias_name = 'Eiru'; reason = 'portfolio_name_variant'; confidence = 'medium' }
)

$taxonomyRows = @(
    [pscustomobject]@{ startup_id='unibaio'; startup_name='Unibaio'; macro_theme='ag biologicals and crop resilience'; emergent_theme='ag biologicals and crop resilience'; market_label='crop protection and nutrition nanodelivery'; technical_stack='nano vehicles; crop protection; crop nutrition'; transition_function='less-efficient-agrochemical-delivery-to-targeted-crop-protection-and-nutrition'; output_class='ag enabling platform'; feedstock='crop protection and nutrition workflows'; industry_destination='agriculture'; market_interface='ag technology platform'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes nano vehicles to enhance crop protection and nutrition.'; confidence='0.80' }
    [pscustomobject]@{ startup_id='biometallum'; startup_name='BioMetallum'; macro_theme='climate, energy and resource systems'; emergent_theme='resource recovery and bioremediation systems'; market_label='sustainable mining biotech'; technical_stack='biotech for mining sustainability; resource recovery'; transition_function='more-extractive-mining-to-biologically-enabled-sustainable-mining'; output_class='industrial solution'; feedstock='mining systems'; industry_destination='mining and resource extraction'; market_interface='industrial solution supplier'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes sustainable mining.'; confidence='0.76' }
    [pscustomobject]@{ startup_id='oncoliq'; startup_name='Oncoliq'; macro_theme='diagnostics and medtech'; emergent_theme='health diagnostics and medtech'; market_label='non-invasive early cancer detection'; technical_stack='non-invasive detection; oncology diagnostics'; transition_function='late-invasive-cancer-detection-to-earlier-non-invasive-screening'; output_class='diagnostic platform'; feedstock='oncology diagnostic workflows'; industry_destination='healthcare diagnostics'; market_interface='diagnostic company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes non-invasive early cancer detection.'; confidence='0.82' }
    [pscustomobject]@{ startup_id='m4life'; startup_name='M4Life'; macro_theme='ag biologicals and crop resilience'; emergent_theme='ag biologicals and crop resilience'; market_label='abiotic stress plant resilience enhancer'; technical_stack='biological plant resilience enhancer; abiotic stress'; transition_function='stress-vulnerable-crops-to-biologically-enhanced-resilience'; output_class='ag biological'; feedstock='crop stress response systems'; industry_destination='agriculture'; market_interface='input supplier'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes a biological plant resilience enhancer to abiotic stress.'; confidence='0.81' }
    [pscustomobject]@{ startup_id='dharma_bioscience'; startup_name='Dharma BioScience'; macro_theme='therapeutics and regenerative medicine'; emergent_theme='therapeutic and regenerative biology'; market_label='non-invasive tissue regeneration'; technical_stack='tissue regeneration; regenerative biotech'; transition_function='invasive-or-limited-tissue-repair-to-regenerative-biological-recovery'; output_class='regenerative therapeutic'; feedstock='tissue regeneration biology'; industry_destination='regenerative medicine'; market_interface='therapeutic company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes non-invasive tissue regeneration.'; confidence='0.82' }
    [pscustomobject]@{ startup_id='mycorium_biotech'; startup_name='Mycorium Biotech'; macro_theme='biobased chemistry and advanced materials'; emergent_theme='biobased chemistry and materials'; market_label='mycelium bio-leather from waste'; technical_stack='mycelium; waste upcycling; biomaterials'; transition_function='waste-and-animal-or-fossil-materials-to-mycelium-based-alternatives'; output_class='biomaterial'; feedstock='waste streams and mycelium'; industry_destination='materials and fashion'; market_interface='material company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes upcycling waste using mycelium to produce bio-leather.'; confidence='0.84' }
    [pscustomobject]@{ startup_id='inmet'; startup_name='INMET'; macro_theme='biobased chemistry and advanced materials'; emergent_theme='biobased chemistry and materials'; market_label='fully compostable solvent-free biopolymer'; technical_stack='biopolymer; compostable materials; solvent-free formulation'; transition_function='fossil-and-solvent-intensive-materials-to-compostable-biopolymers'; output_class='biopolymer material'; feedstock='biopolymer chemistry'; industry_destination='materials and packaging'; market_interface='material company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes a fully compostable, solvent free biopolymer.'; confidence='0.82' }
    [pscustomobject]@{ startup_id='notfossil'; startup_name='NotFossil'; macro_theme='climate, energy and resource systems'; emergent_theme='resource recovery and bioremediation systems'; market_label='biofilters for hydrocarbon degradation'; technical_stack='proprietary microbes; biofilters; hydrocarbon degradation'; transition_function='polluting-hydrocarbon-management-to-biological-degradation-and-remediation'; output_class='bioremediation system'; feedstock='hydrocarbon-contaminated flows'; industry_destination='energy and environmental remediation'; market_interface='industrial solution supplier'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes biofilters with proprietary microbes to degrade hydrocarbons.'; confidence='0.84' }
    [pscustomobject]@{ startup_id='eiru'; startup_name='Eirú'; macro_theme='ag biologicals and crop resilience'; emergent_theme='ag biologicals and crop resilience'; market_label='advanced pollination optimization'; technical_stack='simulated bee dynamics; pollination optimization'; transition_function='lower-pollination-efficiency-to-biology-informed-optimization'; output_class='ag biological optimization system'; feedstock='pollination dynamics'; industry_destination='agriculture'; market_interface='ag technology platform'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes advanced pollination optimization through simulated bee dynamics.'; confidence='0.78' }
    [pscustomobject]@{ startup_id='libera'; startup_name='Libera'; macro_theme='therapeutics and regenerative medicine'; emergent_theme='therapeutic and regenerative biology'; market_label='extracellular vesicles for inflammatory disease'; technical_stack='extracellular vesicles; inflammatory disease therapeutics'; transition_function='limited-inflammatory-disease-treatment-to-vesicle-based-biological-therapies'; output_class='therapeutic platform'; feedstock='extracellular vesicles'; industry_destination='therapeutics'; market_interface='therapeutic company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes extracellular vesicles to fight inflammatory diseases.'; confidence='0.83' }
    [pscustomobject]@{ startup_id='trebe_biotech'; startup_name='Trebe Biotech'; macro_theme='food biotech and novel ingredients'; emergent_theme='food transition ingredients and proteins'; market_label='affordable complex proteins'; technical_stack='complex protein production; biotech manufacturing'; transition_function='expensive-hard-to-access-complex-proteins-to-simpler-affordable-production'; output_class='protein ingredient platform'; feedstock='protein production workflows'; industry_destination='food and biotech ingredients'; market_interface='ingredient company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='sf500_portfolio_official'; evidence_source='sf500_portfolio_2026'; notes='SF500 portfolio describes complex proteins made simple and affordable.'; confidence='0.76' }
)

$profileRows = @(
    [pscustomobject]@{ startup_id='unibaio'; startup_name='Unibaio'; startup_summary_v1='Startup agtech que desarrolla nano vehiculos para mejorar proteccion y nutricion de cultivos. Entra en tesis por su acople directo con productividad y resiliencia agricola material.'; business_one_liner='Nano vehicles to enhance crop protection and nutrition.'; problem_addressed='Baja precision y menor desempeno en estrategias de proteccion y nutricion de cultivos.'; technical_approach='Nano vehiculos para mejorar entrega y eficacia en proteccion y nutricion vegetal.'; industry_destination='Agriculture'; materiality_signal='high'; thesis_scope_note='Entra por intervencion material directa sobre sistemas agricolas.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes nano vehicles to enhance crop protection and nutrition.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='biometallum'; startup_name='BioMetallum'; startup_summary_v1='Startup orientada a mineria sostenible. Entra en tesis por su interfaz con recuperacion de recursos y transformacion material de sistemas extractivos.'; business_one_liner='Sustainable mining.'; problem_addressed='Procesos extractivos con mayor carga ambiental y menor sostenibilidad en mineria.'; technical_approach='Soluciones biotech para mejorar sostenibilidad de operaciones mineras.'; industry_destination='Mining and resource extraction'; materiality_signal='high'; thesis_scope_note='Entra por resource systems y limites planetarios, aunque requiere luego mas detalle tecnico.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes sustainable mining.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='oncoliq'; startup_name='Oncoliq'; startup_summary_v1='Startup de diagnostico oncologico no invasivo para deteccion temprana de cancer. Entra en tesis por diagnostics and medtech.'; business_one_liner='Non-invasive early cancer detection.'; problem_addressed='Diagnostico tardio o invasivo en cancer.'; technical_approach='Herramientas diagnosticas no invasivas orientadas a deteccion temprana.'; industry_destination='Healthcare diagnostics'; materiality_signal='high'; thesis_scope_note='Entra por diagnostica clinica biologicamente acoplada.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes non-invasive early cancer detection.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='m4life'; startup_name='M4Life'; startup_summary_v1='Startup agrobiotech que desarrolla un enhancer biologico para resiliencia vegetal frente a estres abiotico. Entra en tesis por ag biologicals and crop resilience.'; business_one_liner='Biological plant resilience enhancer to abiotic stress.'; problem_addressed='Vulnerabilidad de cultivos frente a estres abiotico.'; technical_approach='Solucion biologica para aumentar resiliencia vegetal.'; industry_destination='Agriculture'; materiality_signal='high'; thesis_scope_note='Entra por bioinsumos y resiliencia material del sistema agricola.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes a biological plant resilience enhancer to abiotic stress.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='dharma_bioscience'; startup_name='Dharma BioScience'; startup_summary_v1='Startup de medicina regenerativa centrada en regeneracion tisular no invasiva. Entra en tesis por therapeutics and regenerative medicine.'; business_one_liner='Non-invasive tissue regeneration.'; problem_addressed='Opciones limitadas o invasivas para reparar tejido dañado.'; technical_approach='Aproximacion biologica de regeneracion tisular.'; industry_destination='Regenerative medicine'; materiality_signal='high'; thesis_scope_note='Entra por biologia regenerativa, no por software.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes non-invasive tissue regeneration.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='mycorium_biotech'; startup_name='Mycorium Biotech'; startup_summary_v1='Startup de biomateriales que upcyclea residuos con micelio para producir bio-leather. Entra en tesis por biobased chemistry and advanced materials.'; business_one_liner='Upcycling waste using mycelium to produce bio-leather.'; problem_addressed='Residuos subutilizados y materiales con mayor huella fosil o animal.'; technical_approach='Uso de micelio para transformar residuos en biomateriales.'; industry_destination='Materials and fashion'; materiality_signal='high'; thesis_scope_note='Entra por transicion material clara y biomateriales.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes upcycling waste using mycelium to produce bio-leather.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='inmet'; startup_name='INMET'; startup_summary_v1='Startup de materiales que desarrolla un biopolimero totalmente compostable y libre de solventes. Entra en tesis por biobased chemistry and advanced materials.'; business_one_liner='Fully compostable, solvent free, biopolymer.'; problem_addressed='Dependencia de materiales menos compostables y procesos con solventes.'; technical_approach='Desarrollo de biopolimeros compostables y solvent free.'; industry_destination='Materials and packaging'; materiality_signal='high'; thesis_scope_note='Entra por sustitucion material y quimica más compatible con limites planetarios.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes a fully compostable, solvent free, biopolymer.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='notfossil'; startup_name='NotFossil'; startup_summary_v1='Startup de bioremediacion que desarrolla biofiltros con microbios propietarios para degradar hidrocarburos. Entra en tesis por climate, energy and resource systems.'; business_one_liner='Biofilters with proprietary microbes to degrade hydrocarbons.'; problem_addressed='Persistencia de hidrocarburos y remediacion menos eficiente de contaminacion asociada.'; technical_approach='Biofiltros y microbios propietarios para degradacion biologica de hidrocarburos.'; industry_destination='Energy and environmental remediation'; materiality_signal='high'; thesis_scope_note='Entra por intervencion biologica concreta sobre flujos materiales contaminantes.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes biofilters development with proprietary microbes to degrade hydrocarbons.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='eiru'; startup_name='Eirú'; startup_summary_v1='Startup agtech enfocada en optimizacion avanzada de polinizacion mediante dinamicas simuladas de abejas. Entra en tesis por su acople directo con rendimiento y resiliencia agricola.'; business_one_liner='Advanced pollination optimization through simulated bee dynamics.'; problem_addressed='Baja eficiencia de polinizacion y menor rendimiento en sistemas productivos dependientes de polinizadores.'; technical_approach='Modelado y simulacion de dinamicas de abejas para optimizar polinizacion.'; industry_destination='Agriculture'; materiality_signal='high'; thesis_scope_note='Entra por interfaz con sistemas vivos y produccion agricola, aunque requiere luego más detalle del stack.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes advanced pollination optimization through simulated bee dynamics.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='libera'; startup_name='Libera'; startup_summary_v1='Startup therapeutics que usa vesiculas extracelulares para combatir enfermedades inflamatorias. Entra en tesis por therapeutics and regenerative medicine.'; business_one_liner='Extracellular vesicles to fight inflammatory diseases.'; problem_addressed='Necesidad de terapias mas efectivas frente a enfermedades inflamatorias.'; technical_approach='Uso de vesiculas extracelulares como enfoque terapeutico biologico.'; industry_destination='Therapeutics'; materiality_signal='high'; thesis_scope_note='Entra por biologia terapeutica clara y no por software o mercado generalista.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes extracellular vesicles to fight inflammatory diseases.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='trebe_biotech'; startup_name='Trebe Biotech'; startup_summary_v1='Startup que busca hacer mas simples y accesibles las proteinas complejas. Entra en tesis por food biotech and novel ingredients como plataforma ligada a produccion biologica de proteinas.'; business_one_liner='Complex proteins, simple and affordable.'; problem_addressed='Complejidad y alto costo en produccion o acceso a proteinas complejas.'; technical_approach='Plataforma biotech para volver mas simples y asequibles las proteinas complejas.'; industry_destination='Food and biotech ingredients'; materiality_signal='medium'; thesis_scope_note='Entra como plataforma de proteinas complejas; conviene luego precisar mejor su destino final.'; source_url=$portfolioUrl; source_type='official_portfolio_profile'; source_date='2026-04-20'; evidence_excerpt='SF500 portfolio describes complex proteins, simple and affordable.'; summary_confidence='medium'; review_status='seeded' }
)

Upsert-AliasRows -Path (Join-Path $Root 'staging\manual_alias_overrides.csv') -Rows $aliasRows
Upsert-CsvById -Path (Join-Path $Root 'quality\manual_startup_taxonomy_overrides.csv') -Rows $taxonomyRows
Upsert-CsvById -Path (Join-Path $Root 'quality\manual_startup_profile_overrides.csv') -Rows $profileRows

Write-Output "SF500 portfolio sweep applied."
