param(
    [string]$Root = "C:\Users\Pablo A\Documents\Codex\2026-04-18-summarize-what-s-happening-on-slack"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Upsert-CsvById {
    param(
        [string]$Path,
        [object[]]$Rows
    )

    $existing = if (Test-Path -LiteralPath $Path) { Import-Csv -LiteralPath $Path } else { @() }
    $map = @{}
    foreach ($row in $existing) {
        $map[[string]$row.startup_id] = $row
    }
    foreach ($row in $Rows) {
        $map[[string]$row.startup_id] = $row
    }
    $map.Values | Sort-Object startup_name | Export-Csv -LiteralPath $Path -NoTypeInformation -Encoding UTF8
}

$taxonomyRows = @(
    [pscustomobject]@{ startup_id='tech'; startup_name='@Tech'; macro_theme='precision agriculture and resource intelligence'; emergent_theme='precision agriculture intelligence'; market_label='animal protein optimization and traceability'; technical_stack='AI; data science; IoT; smart ear tags'; transition_function='lower-efficiency-animal-protein-production-to-data-driven-optimization'; output_class='animal production intelligence platform'; feedstock='livestock and animal protein production data'; industry_destination='animal protein supply chains'; market_interface='B2B platform'; scope_decision='include'; scope_reason='official_portfolio_signal_biocentric_material_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes optimization of animal protein production using AI, IoT and traceability across cattle, broiler and fish.'; confidence='0.78' }
    [pscustomobject]@{ startup_id='agree'; startup_name='Agree'; macro_theme='climate, energy and resource systems'; emergent_theme='traceability and tokenized resource infrastructure'; market_label='agri-food chain traceability and market infrastructure'; technical_stack='B2B marketplace; traceability; sustainability workflows'; transition_function='fragmented-agri-food-chains-to-digital-traceable-coordination'; output_class='market and traceability platform'; feedstock='grains, oilseeds, fruits and vegetables transaction data'; industry_destination='agri-food chains'; market_interface='B2B platform'; scope_decision='include'; scope_reason='official_portfolio_signal_material_ag_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes a B2B platform for agri-food chains with traceability and sustainability.'; confidence='0.80' }
    [pscustomobject]@{ startup_id='agroforte'; startup_name='Agroforte'; macro_theme='climate, energy and resource systems'; emergent_theme='traceability and tokenized resource infrastructure'; market_label='animal production financial infrastructure'; technical_stack='digital bank; credit risk; production data'; transition_function='capital-constrained-livestock-producers-to-better-infrastructure-and-welfare'; output_class='financial infrastructure platform'; feedstock='poultry, pork and dairy production data'; industry_destination='animal protein supply chains'; market_interface='B2B finance platform'; scope_decision='include'; scope_reason='official_portfolio_signal_material_ag_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes a digital banking and credit platform for poultry, pork and dairy producers, improving infrastructure and animal welfare.'; confidence='0.68' }
    [pscustomobject]@{ startup_id='bemagro'; startup_name='BemAgro'; macro_theme='precision agriculture and resource intelligence'; emergent_theme='precision agriculture intelligence'; market_label='high-resolution field intelligence platform'; technical_stack='remote sensing; geospatial analytics; agronomic intelligence'; transition_function='low-resolution-farm-management-to-precision-field-intelligence'; output_class='farm intelligence platform'; feedstock='high-resolution agricultural and field data'; industry_destination='crop production and farm operations'; market_interface='B2B software platform'; scope_decision='include'; scope_reason='official_portfolio_signal_material_ag_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes BemAgro as transforming high-resolution data into actionable field intelligence from planning to harvest optimization.'; confidence='0.82' }
    [pscustomobject]@{ startup_id='incluirtec'; startup_name='Incluirtec'; macro_theme='climate, energy and resource systems'; emergent_theme='traceability and tokenized resource infrastructure'; market_label='agrifintech infrastructure for smallholder inclusion'; technical_stack='agrifintech-as-a-service; risk and rural finance workflows'; transition_function='underserved-rural-producers-to-data-enabled-financial-access'; output_class='rural financial infrastructure platform'; feedstock='smallholder farm and productive segment data'; industry_destination='smallholder agriculture and rural productive systems'; market_interface='B2B fintech infrastructure'; scope_decision='include'; scope_reason='official_portfolio_signal_material_ag_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes IncluirTec as an agrifintech-as-a-service enabling financial institutions to serve smallholder farmers and rural productive segments.'; confidence='0.74' }
    [pscustomobject]@{ startup_id='culttivo'; startup_name='Culttivo'; macro_theme='climate, energy and resource systems'; emergent_theme='traceability and tokenized resource infrastructure'; market_label='coffee producer climate-aware credit platform'; technical_stack='satellite imagery; analytics; climate risk scoring; ESG underwriting'; transition_function='opaque-coffee-credit-to-data-driven-rural-finance'; output_class='ag financial intelligence platform'; feedstock='coffee farm production, climate and ESG data'; industry_destination='coffee production and rural finance'; market_interface='B2B/B2F platform'; scope_decision='include'; scope_reason='official_portfolio_signal_material_ag_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes Culttivo as a digital platform delivering efficient, transparent credit to coffee producers using satellite imagery and climate analytics.'; confidence='0.79' }
    [pscustomobject]@{ startup_id='produzindo-certo'; startup_name='Produzindo Certo'; macro_theme='climate, energy and resource systems'; emergent_theme='traceability and tokenized resource infrastructure'; market_label='agribusiness transparency and compliance platform'; technical_stack='traceability; sustainability verification; producer-company matching'; transition_function='opaque-agribusiness-chains-to-transparent-social-environmental-compliance'; output_class='supply chain transparency platform'; feedstock='farm compliance, traceability and sustainability data'; industry_destination='agribusiness value chains'; market_interface='B2B platform'; scope_decision='include'; scope_reason='official_portfolio_signal_material_ag_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes Produzindo Certo as providing transparency and connecting companies with farmers committed to the highest social and environmental standards.'; confidence='0.78' }
    [pscustomobject]@{ startup_id='cerradox'; startup_name='CerradoX'; macro_theme='precision agriculture and resource intelligence'; emergent_theme='precision agriculture intelligence'; market_label='AI agricultural production platform for underused land'; technical_stack='AI; agricultural planning; farm standardization workflows'; transition_function='underused-land-to-standardized-industry-ready-production'; output_class='ag production intelligence platform'; feedstock='land-use, production and farm standardization data'; industry_destination='small and mid-sized farming operations'; market_interface='B2B platform'; scope_decision='include'; scope_reason='official_portfolio_signal_material_ag_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes CerradoX as the first AI-driven agricultural platform for small and mid-sized farmers in Brazil, turning underused land into standardized production.'; confidence='0.77' }
    [pscustomobject]@{ startup_id='verqor'; startup_name='Verqor'; macro_theme='climate, energy and resource systems'; emergent_theme='traceability and tokenized resource infrastructure'; market_label='digital agricultural finance platform'; technical_stack='digital finance; agricultural credit workflows'; transition_function='traditional-ag-finance-to-digital-accessible-capital'; output_class='ag finance platform'; feedstock='agricultural producer and financing data'; industry_destination='agriculture and rural finance'; market_interface='B2B/B2F platform'; scope_decision='include'; scope_reason='official_portfolio_signal_material_ag_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes Verqor as driving the digital transformation of agriculture in Mexico through innovative financial solutions.'; confidence='0.74' }
    [pscustomobject]@{ startup_id='blooms'; startup_name='Blooms'; macro_theme='climate, energy and resource systems'; emergent_theme='traceability and tokenized resource infrastructure'; market_label='agricultural exporter finance platform'; technical_stack='export finance; working capital; trade finance'; transition_function='constrained-ag-export-finance-to-comprehensive-digital-solutions'; output_class='ag export finance platform'; feedstock='agricultural exporter transaction and risk data'; industry_destination='agricultural export supply chains'; market_interface='B2B finance platform'; scope_decision='include'; scope_reason='official_portfolio_signal_material_ag_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes Blooms Capital as a fintech dedicated to agricultural exporters with comprehensive financial solutions.'; confidence='0.72' }
    [pscustomobject]@{ startup_id='agricapital'; startup_name='Agricapital'; macro_theme='climate, energy and resource systems'; emergent_theme='traceability and tokenized resource infrastructure'; market_label='smallholder agricultural financing platform'; technical_stack='ag credit; risk assessment; rural finance partnerships'; transition_function='limited-rural-credit-to-fast-tailored-ag-financing'; output_class='rural finance platform'; feedstock='small farmer credit and production data'; industry_destination='smallholder agriculture'; market_interface='B2B/B2F platform'; scope_decision='include'; scope_reason='official_portfolio_signal_material_ag_system'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes AgriCapital as Colombia first fintech focused on agricultural financing for small farmers.'; confidence='0.75' }
    [pscustomobject]@{ startup_id='phagelab'; startup_name='PhageLab'; macro_theme='ag biologicals and crop resilience'; emergent_theme='ag biologicals and crop resilience'; market_label='bacteriophage animal health platform'; technical_stack='bacteriophages; AI; pathogen diagnostics; livestock health biotech'; transition_function='broad-antibiotic-use-to-targeted-biological-pathogen-control'; output_class='animal health biotech platform'; feedstock='livestock pathogens, bacterial samples and farm health data'; industry_destination='poultry, livestock and animal health'; market_interface='B2B animal health company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes PhageLab as a global biotech company developing tailor-made antibacterial solutions for poultry and livestock producers with AI-powered diagnosis.'; confidence='0.90' }
    [pscustomobject]@{ startup_id='heartbest'; startup_name='Heartbest'; macro_theme='food biotech and novel ingredients'; emergent_theme='food transition ingredients and proteins'; market_label='plant-based dairy foodtech'; technical_stack='plant-based dairy formulation; food technology'; transition_function='animal-dairy-to-plant-based-food-systems'; output_class='food product platform'; feedstock='amaranth and plant-based ingredient systems'; industry_destination='food and beverage'; market_interface='consumer food company'; scope_decision='include'; scope_reason='official_portfolio_signal_bio_based_or_biocentric'; scope_source='yieldlab_portfolio_official'; evidence_source='yieldlab_portfolio_2026'; notes='The Yield Lab Latam portfolio describes plant-based dairy products built directly from plants for a healthier and more sustainable food system.'; confidence='0.84' }
)

$profileRows = @(
    [pscustomobject]@{ startup_id='tech'; startup_name='@Tech'; startup_summary_v1='Startup agtech que usa IA, data science e IoT para optimizar la produccion de proteina animal y trazar animales a lo largo de la cadena. Entra en tesis por su acople biocentrico y material a sistemas vivos de produccion animal.'; business_one_liner='Animal protein optimization and traceability with AI and IoT.'; problem_addressed='Ineficiencias productivas y baja trazabilidad en cadenas de proteina animal.'; technical_approach='Plataforma con IA, vision computacional, IoT y etiquetas inteligentes para monitoreo y decision.'; industry_destination='Animal protein supply chains'; materiality_signal='high'; thesis_scope_note='Entra por operar sobre sistemas vivos y cadenas materiales de proteina animal, no por software horizontal.'; source_url='https://theyieldlablatam.com/companies/atech/'; source_type='official_portfolio_profile'; source_date='2026-04-21'; evidence_excerpt='The Yield Lab Latam portfolio describes optimization of animal protein production with AI, data science, IoT and smart ear tags for traceability.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='agree'; startup_name='Agree'; startup_summary_v1='Plataforma B2B para cadenas agroalimentarias con foco en trazabilidad, sostenibilidad y coordinación comercial de granos, oleaginosas, frutas y verduras. Entra en tesis por su fuerte acople a cadenas materiales agroalimentarias.'; business_one_liner='Agri-food chain traceability and market infrastructure.'; problem_addressed='Fragmentacion comercial, baja trazabilidad y menor coordinación en cadenas agroalimentarias.'; technical_approach='Marketplace B2B y herramientas digitales para coordinación, trazabilidad y soluciones comerciales/financieras en agro.'; industry_destination='Agri-food chains'; materiality_signal='medium'; thesis_scope_note='Entra como infraestructura de trazabilidad y coordinación material del sistema agroalimentario.'; source_url='https://theyieldlablatam.com/companies/agree/'; source_type='official_portfolio_profile'; source_date='2026-04-21'; evidence_excerpt='The Yield Lab Latam portfolio describes a platform to accelerate digital transformation in agri-food chains with traceability and sustainability.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='agroforte'; startup_name='Agroforte'; startup_summary_v1='Infraestructura financiera digital para pequeños y medianos productores de aves, cerdos y lácteos. La dejamos adentro por su acople directo con sistemas productivos animales, infraestructura rural y bienestar animal, aunque es un caso de borde más discutible que el núcleo biotech.'; business_one_liner='Animal production financial infrastructure.'; problem_addressed='Restricciones de crédito e infraestructura en productores pecuarios integrados.'; technical_approach='Plataforma digital de crédito y gestión de riesgo basada en datos históricos de producción.'; industry_destination='Animal protein supply chains'; materiality_signal='medium'; thesis_scope_note='Caso borde: entra por infraestructura directamente acoplada a producción animal y bienestar, no por fintech generalista.'; source_url='https://theyieldlablatam.com/companies/agroforte/'; source_type='official_portfolio_profile'; source_date='2026-04-21'; evidence_excerpt='The Yield Lab Latam portfolio describes a digital bank for poultry, pork and dairy producers improving infrastructure, supply chain strength and animal health and welfare.'; summary_confidence='medium'; review_status='seeded' }
    [pscustomobject]@{ startup_id='heartbest'; startup_name='Heartbest'; startup_summary_v1='FoodTech enfocada en productos lácteos plant-based como quesos, leches y spreads. Entra en tesis por transición material desde sistemas lácteos animales hacia alimentos de base vegetal.'; business_one_liner='Plant-based dairy foodtech.'; problem_addressed='Dependencia de sistemas lacteos animales con mayor huella ambiental y menor flexibilidad alimentaria.'; technical_approach='Desarrollo de portfolio de alimentos plant-based con foco en equivalencias sensoriales y nutricionales.'; industry_destination='Food and beverage'; materiality_signal='high'; thesis_scope_note='Entra de forma clara por food transition y biobased food systems.'; source_url='https://theyieldlablatam.com/companies/heartbest/'; source_type='official_portfolio_profile'; source_date='2026-04-21'; evidence_excerpt='The Yield Lab Latam portfolio describes revolutionary plant-based dairy products built directly from plants for a healthier and more sustainable food system.'; summary_confidence='medium'; review_status='seeded' }
)

Upsert-CsvById -Path (Join-Path $Root 'quality\manual_startup_taxonomy_overrides.csv') -Rows $taxonomyRows
Upsert-CsvById -Path (Join-Path $Root 'quality\manual_startup_profile_overrides.csv') -Rows $profileRows

Write-Output "The Yield Lab Latam portfolio sweep applied."
